### ISSUE TITLE
supertokens-node 2.0.0 - 2.0.2 exports nothing

### ISSUE THREAD

**Issue by stephanoparaskeva** [supertokens/supertokens-node#1]
## Version: 
` "supertokens-node": "^2.0.2" `

## Example
```JavaScript
import supertokens from 'supertokens-node';
console.log(supertokens);
```
#### Result:
`undefined`

**Comment by rishabhpoddar** [comment]
Hi Stephano,

You should use `import * as supertokens from "supertokens-node"`

If using older versions of JS, then it is `let supertokens = require("supertokens-node")`
