### ISSUE TITLE
(Intermediate) Verify ID token sent by Auth0 in login API

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#10]
The `idToken` returned [here](https://github.com/supertokens/supertokens-node/blob/fc7abe7137f59ce804c367473fd8fbc9d82caa34/lib/ts/express.ts#L343) from Auth0 needs to be verified using Auth0's public key for that domain (passed in the argument). 

For example, if the domain is `dev-3myi6b3e.us.auth0.com`, the public key can be found at `https://dev-3myi6b3e.us.auth0.com/.well-known/jwks.json`.

**Comment by aaayushsingh** [comment]
Hi, I can contribute if no one else is working on it. Can you point me in the right direction for this?

I see this already implemented [here](https://github.com/supertokens/supertokens-node/blob/fc7abe7137f59ce804c367473fd8fbc9d82caa34/lib/ts/express.ts#L328). Does this need a separate implementation somewhere else?

**Comment by rishabhpoddar** [comment]
Hello @aaayushsingh. Yes, this issue needs work. Please see the updated first comment for more info :)

I have assigned this issue to you.

**Comment by aaayushsingh** [comment]
> For example, if the domain is dev-3myi6b3e.us.auth0.com, the public key can be found at https://dev-3myi6b3e.us.auth0.com/.well-known/jwks.json

Does the data here change over time? Should I make a network call each time or can this be cached/stored locally? Maybe make it optional using envs?

**Comment by rishabhpoddar** [comment]
> Should I make a network call each time or can this be cached/stored locally?

We should make a network call each time since this call occurs relatively rarely (on user login or session refresh). This can be optimised to use a cache later on if we see an issue.

> Does the data here change over time?

Auth0 says it's possible, but since we will be fetching each time, this doesn't really matter.

**Comment by rishabhpoddar** [comment]
Not valid anymore.
