### ISSUE TITLE
Add fastify support

### ISSUE THREAD

**Issue by ankitjena** [supertokens/supertokens-node#114]
## Description
Currently `supertokens-node` only supports express. Express is quite popular, but has it's downsides. Fastify on the other is a really cool framework. I tried applying the instructions to setup backend, but the middleware approach of express causes an issue. Even tried using `fastify-express` to apply the supertoken middleware but that throws an error as well as the function is not compatible. 

## Plugin
Fastify has a plugin approach, rather than middleware approach. Supertokens can have a plugin for the routes middleware and errorhandler instead of it being a middleware. 

This will be a good addition imo. Otherwise supertokens is quite restricting.

**Comment by rishabhpoddar** [comment]
Can you also please post the error you get when you try and use `fastify-express`

**Comment by ankitjena** [comment]
It's a Typescript error,
```
Argument of type '(request: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, response: Response<any, Record<string, any>>, next: NextFunction) => Promise<...>' is not assignable to parameter of type 'Handler'.
  Type '(request: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, response: Response<any, Record<string, any>>, next: NextFunction) => Promise<...>' is not assignable to type 'SimpleHandleFunction'.ts(2345)
```

**Comment by rishabhpoddar** [comment]
This is related to https://github.com/supertokens/supertokens-node/issues/123

**Comment by bhumilsarvaiya** [comment]
fastify framework support will be added once PR #146 is merged
