### ISSUE TITLE
Support for vercel serverless functions

### ISSUE THREAD

**Issue by tobiasdiez** [supertokens/supertokens-node#118]
I just setup supertokens with vercel. Mostly, I followed the documentation [for netlify](https://supertokens.io/docs/emailpassword/serverless/with-netlify/about). The only changes necessary were that one needs to create a `api/index.js` file with the following content (which is almost the same as for netlify)
```js
const express = require("express");
let supertokens = require("supertokens-node");
let EmailPassword = require('supertokens-node/recipe/emailpassword');
let Session = require('supertokens-node/recipe/session')

const app = express();

supertokens.init(...);

app.use(supertokens.middleware());

app.use(supertokens.errorHandler());

module.exports = app;
```
and that one needs to create (or change an existing) `vercel.json` in the root with the content
```json
{
    "rewrites": [{ "source": "/api/(.*)", "destination": "/api" }]
}  
```

It might be a good idea to add this to the documentation.

Moreover, in contrast to netlify, in vercel one usually does not provide a full express instance. The preferred way would be to have simple serverless functions for each functionality (e.g. `api/signin`). I tried to implement this, but this seems currently rather hard because the `supertokens` instance doesn't provide shortcut functions for common functionality, i.e. a `signup` function that takes only the `request` and `response` as a parameters.

**Comment by rishabhpoddar** [comment]
Thanks! You can try using `serverless-http` to convert a serverless function into an express app - that's what is done for netlify as well as seen here: https://supertokens.io/docs/emailpassword/serverless/with-netlify/auth-serverless

**Comment by tobiasdiez** [comment]
`serverless-http` is not needed for vercel, one can just directly return the `express` instance and everything works (as in the above code). It's just that this is not the recommended way, and a function along the lines of the following code is more what one would expect in vercel:
```js
let supertokens = require("supertokens-node");
module.exports = (req, res) => {
  supertokens.init(...);
  supertokens.signup(req, res);
}
```
in `api/signup.js`, and similarly for the other endpoints. Such a flexible approach would probably also be helpful in other projects, if one wants to control the exact location of the api endpoints, and/or would like to post/pre-process certain operations.

**Comment by rishabhpoddar** [comment]
Ah got it. Thanks! 

> Such a flexible approach would probably also be helpful in other projects, if one wants to control the exact location of the api endpoints

We don't allow users to change the full path of the APIs we provide (they can scope our APIs though). The reason is that if they could change any API path, they would have to communicate that info on a per API basis to the frontend, which would add more documentation, more work etc..

> and/or would like to post/pre-process certain operations.
Yes. This we plan on providing very soon, but it would still all by in the express app style as you had initially pointed out

**Comment by tobiasdiez** [comment]
Fair enough! 

(The idea for customizable endpoints was also more in the context where the developer wants to use supertoken as a backend, but decides to manually implement the frontend. But I understand that this use-case is not the recommended way of using supertokens.)

**Comment by rishabhpoddar** [comment]
We have added this to our docs: https://supertokens.com/docs/thirdpartyemailpassword/serverless/with-vercel/about (along with a blog post)
