### ISSUE TITLE
Extract away framework specific usage from the core logic

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#123]
- So that we can add wrappers for express, aws lambda, nestJS etc.. easily.
- The project should not have to depend on any of these frameworks explicitly. But dev dependencies are OK
- We will need to add tests for each framework as well
- Note: In authorisationURL API, key-value takes req object

**Comment by bhumilsarvaiya** [comment]
Following frameworks will be supported once PR #146 is merged:
- express
- hapi
- fastify
- awsLambda
- koa
- loopback
