### ISSUE TITLE
Forcing users to be logged out by querying without a CSRF token

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#141]
- In the refresh API, if we query the API without the anti-csrf token, the the user might get logged out cause we throw unauthorised error which clears the session cookies

**Comment by rishabhpoddar** [comment]
Analysis of this attack vector:

## If using custom header as a way to prevent CSRF
- This is only secure if CORS is set correctly - to allow requests from only known domains.
- So if an attacker manages to query the refresh API without a custom domain (via a third party site), then the browser won't allow the request to go through in the first place.
- Hence this is protected already

## If using anti-csrf token
- Then it may be that the CORS setting allows any domain to query the API, in which case, the `/auth/session/refresh POST` will go through.
- The SDK will clear the cookies, and the user will be logged out.
- If we do not clear the cookies, then the user will be unaffected. However, in browsers like Safari, where the frontend set cookies are removed every 7 days, this will leave users in a "stuck" state where they can't use the app, nor can they logout and login again - unless the frontend SDK removes the front set tokens anyway (on session expiry status code to refresh API call)

**Comment by porcellus** [comment]
Upon later review we've decided that:
- we see no reason to skip clearing tokens if it's a CSRF failure
- Overall, this makes maintaining a consistent state across HTTPOnly and frontend cookies easier
  - this way 401 responses during session refresh will always mean that the session doesn't exists
  - the frontend SDKs this way can (and do) handle the refresh endpoint responding with a 401 by clearing all tokens.
