### ISSUE TITLE
Change in OAuth scopes

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#148]
- Need to recheck if we are actually asking for the minimum scope or not
- If the user providers their own scope array, should we not use ours at all? In case they don't ask for the minimum scope, then we through an error since we can't get the profile info.
- This is a breaking change.

**Comment by bhumilsarvaiya** [comment]
changes will be merged once PR #155 is merged. changes will be available from version 7.x onwards.

**Comment by rishabhpoddar** [comment]
Closing this issue since it has been merged already.
