### ISSUE TITLE
Issue when frontend is using `sendBeacon` and session verification is optional

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#156]
## Issue 1:
If a session exists, but the access token has expired, using `sendBeacon` will only cause the `sIdRefreshToken` to be sent to the backend (no access token, no `rid` header, no `anti-csrf` token).

Even if the session is marked as optional, it will still throw a try refresh token exception since `sIdRefreshToken` exists. However, the frontend will not be able to refresh the session since there are no interceptors added to `sendBeacon`.

## Issue 2:
If the access token is there too, then the logic will try and do an anti-csrf check. This will fail, since the `rid` header is missing. The user can solve this by setting `antiCsrf: false`.

This is OK, but the user will need to set `option: true` and  `antiCsrf: false` for it to work fully. Is this a good API?

**Comment by rishabhpoddar** [comment]
#Possible solution for issue 1

Instead of always throwing an error [here](https://github.com/supertokens/supertokens-node/blob/master/lib/ts/recipe/session/recipeImplementation.ts#L94), we should throw only if `options.sessionRequired === true || frontendHasInterceptor`, else we should return `undefined`.

We can know if `frontendHasInterceptor` by checking if the request has the `rid` header. If it does, then `frontendHasInterceptor = true`, else it's `false.`

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar The changes in PR #159 are based on the possible solution suggested by you. Also for the issue mentioned regarding the SSR, one small change in the logic is made where if the `frontendHasInterceptor` is not used but the request method is `GET`, the the function will throw `TRY_REFRESH_TOKEN`.

**idRefreshToken passed** | **accessToken passed** | **Request Method** | **sessionRequired** | **frontendHasInterceptor** | **Try Refresh Error Thrown**
:---: | :---: | :---: | :---: | :---: | :---:
true | false | any | true | true/false | true
true | false | get | false | true/false | true
true | false | any | false | true | true
true | false | non-get | false | false | false

**Comment by rishabhpoddar** [comment]
A better solution for this would be to ask users to use `getSession` explicitly for these "special" APIs, and catch try refresh token errors and treat them as undefined session.
