### ISSUE TITLE
Implement a recipeModule manager

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#16]
Should be responsible for:
- [x] [Routing of an API to a module](https://github.com/supertokens/supertokens-node/issues/16#issuecomment-710163235). The algorithm can be found [here](https://github.com/supertokens/supertokens-node/issues/16#issuecomment-715032475)

- [x] Has a way for any module to get the `appInfo` if needed.

- [x] Has an init function that takes:
   - The `hosts` and `apiKey`
   - The [appInfo](https://github.com/supertokens/supertokens-auth-react/issues/4#issuecomment-709977157)
   - recipeList: moduleInterface[]

- Has error handling routing for modules:
   - [x] If the error has a `rId`:
      - If it matches any one of the module's being used (the first one it finds), call that module's error handler
      - If no modules match, then throw pass the error to the next error handler.
   - [x] The error thrown from a module is:
   ```
   {
      rId: "",
      type: "",
      message: string,
      payload: any
   }
   ```

- [x] Handle CORS headers. Has a function like `getAllCORSHeaders` which:
   - calls the `getAllCORSHeaders` for each module
   - removes duplicates
   - returns the resulting `strings` in an array

- Provides an abstract `recipeModule` class that modules must extend:
   - [x] Provides methods to asks a module if they can handle the current route (excluding `apiBasePath`) via the middleware function.
   - [x] Get and manage the module's `rId`. The `rId` will be an argument to the constructor.
   - [x] Exposes a function that modules must implement to handle the current API request.
   - [x] Gets all CORS headers from a module.
   - [x] Asks a module if they can handle the current error thrown
   - [x] Lets a module handle an error
- [x] Recipe modules must be built such that parent recipe's rId can be propagated to them. [This is how](https://github.com/supertokens/supertokens-node/issues/16#issuecomment-710180103)
- [x] Enforce use of `NormalisedURLDomain` and `NormalisedURLPath`

**Comment by rishabhpoddar** [comment]
@NkxxkN please review the above info. Thanks

**Comment by rishabhpoddar** [comment]
## Routing functionality
```js
import * as supertokens from "supertokens-node";

let app = express();

app.use(supertokens.middleware());

app.use(supertokens.errorHandler());

```

**Comment by rishabhpoddar** [comment]
## If a recipe is being built on top of another one, how can its rId be propogated down?

### Base recipe
```jsx
class EmailPassword extends RecipeModule {
	
	static instance: undefined | EmailPassword

	static __getInstanceIfDefined() => {
		if (instance !== undefined) {
			return instance;
		}
		throw error("please call init..");
	}

	static init(options: {..}): ModuleInterface {
		constructor(options, "emailpassword")
		// create a singleton instance of EmailPassword
	}

	constructor({..}, recipeId) {
		super(recipeId)
		....
	}

	signUp(email, password) {
		let rId = super.getRecipeId();
		// do implementation...
	}

	static signUp(email, password) => {
		let instance = EmailPassword.__getInstanceIfDefined();
		return await instance.signUp(email, passowrd);
	}
}
```

### New recipe
```jsx
class EmailPasswordModified extends RecipeModule {

	static instance: undefined | EmailPasswordModified
	
	emailPasswordInstance: EmailPassword

	constructor({..}, recipeId) {
		super(recipeId)
		this.emailPasswordInstance = new EmailPassword(<options specific to this>, recipeId)
	}

	static __getInstanceIfDefined() => {
		if (instance !== undefined) {
			return instance;
		}
		throw error("please call init..");
	}

	static init(options: {..}): ModuleInterface {
		constructor(options, "emailpasswordmodified")
	}

	static signUp(email, password) => {
		let instance = EmailPasswordModified.__getInstanceIfDefined();
		return await instance.emailPasswordInstance.signUp(email, passowrd)
	}

}
```

**Comment by rishabhpoddar** [comment]
In the config for `supertokens.init`, we do not pass a `recipeModule[]`. Instead, we pass a `(() => RecipeModule)[]` which will allow the recipes to be initialised after the `supertokens.init` has finished initialising info that it has been given.

This implies that the `init` functions of the recipes must not return a `RecipeModule`, but instead, should return a `() => RecipeModule`

**Comment by rishabhpoddar** [comment]
The routing algorithm:
   - If request does not start with `apiBasePath`, skip
   - Case `rid` is present:
      - Loop through all modules to find the one with the matching `rId` (find the first matching one)
         - `rid` doesn't match, then skip.
      - Ask the matching recipe module if they can handle the path and method.
         - If not, then skip
      - Pass the task to the that module
   - Case no `rid` is present:
      - Loop through all modules to find the first one that can handle the task based on the path and method
         - If none, then skip
      - Pass the task to the that module

@NkxxkN , I have written the routing algo in a bit more detail here (in comparison to the one written in the frontend package). It still follows the same login though. Lmk if this is fine with you and if you have done something very differently on the frontend.

**Comment by NkxxkN** [comment]
> Loop through all modules to find the one with the matching rId (find the first matching one

Do you loop through recipes and then through features? i.e. where and how do you store the routes? what's the data structure for it?

Seems to be working from a logic perspective!

**Comment by rishabhpoddar** [comment]
The routing code is [here](https://github.com/supertokens/supertokens-node/pull/25/commits/940b7f1385a36b61fc2a8364d3c23c07dfb39895#diff-f64456657f32f67ff250528818be64dce9c5b3ed93b24b68704bc7465016138aR92)

The notion of a feature is slightly loose in the backend since it's just a bunch of functions and APIs being exposed by each feature. So there isn't really a concept of an explicit feature like there is on the frontend (cause frontend features are much more complex and have themes)

> Do you loop through recipes and then through features?
- Yes. I [loop through each recipe](https://github.com/supertokens/supertokens-node/pull/25/commits/940b7f1385a36b61fc2a8364d3c23c07dfb39895#diff-f64456657f32f67ff250528818be64dce9c5b3ed93b24b68704bc7465016138aR107).
- For each recipe, I then [loop through all the routes](https://github.com/supertokens/supertokens-node/pull/25/commits/940b7f1385a36b61fc2a8364d3c23c07dfb39895#diff-45f2777959707b02289a7ccbf56b008ca9c886a9c3b21498f76f1e513cf7ca2aR55) it has.

> where and how do you store the routes?

The [`abstract` recipe base class](https://github.com/supertokens/supertokens-node/blob/940b7f1385a36b61fc2a8364d3c23c07dfb39895/lib/ts/recipeModule.ts#L22) has an `abstract` function [`getAPIsHandled`](https://github.com/supertokens/supertokens-node/pull/25/commits/940b7f1385a36b61fc2a8364d3c23c07dfb39895#diff-45f2777959707b02289a7ccbf56b008ca9c886a9c3b21498f76f1e513cf7ca2aR70) which returns an array that contains the following object:
```
{
    pathWithoutApiBasePath: string,
    method: HTTPMethod,
    id: string, disabled: boolean
}
```
The actual recipe [implements this function](https://github.com/supertokens/supertokens-node/pull/25/commits/940b7f1385a36b61fc2a8364d3c23c07dfb39895#diff-ca19701f31646e124b56ab92d75c6e1fc5685e6ff8005dabf9d0ae4b5afc8d5aR128) to return the array of these objects - one per support API / route.

**Comment by NkxxkN** [comment]
Ok looks good to me!

**Comment by rishabhpoddar** [comment]
@NkxxkN. I am done with this issue. The PR is https://github.com/supertokens/supertokens-node/pull/25, but since it's a complete rewrite of most of the lib anyway, I am pushing it to branch `3.0`. So you can see the code there if you'd like.

This issue will be in the "To review" section of the v2.6 project, until you have seen it. If you don't want to see it, we can move it to done
