### ISSUE TITLE
Next.js example is slow when protecting a page

### ISSUE THREAD

**Issue by henke443** [supertokens/supertokens-node#163]
When using the protect page wrapper component, loading times increase by 2-3 seconds on my local machine. Even in the production build. When I implement a check using getServerSideProps it loads almost instantly. Why is this?

**Comment by henke443** [comment]
Additionally it added 600 KB to my client bundle size, decided to go with another provider unfortunately.

**Comment by rishabhpoddar** [comment]
> loading times increase by 2-3 seconds on my local machine

This is probably only on first load as the frontend doesn't know if a session exists, and needs to query the backend API. We have not noticed such significant delays ever before. If you run [this example](https://github.com/supertokens/next.js/tree/canary/examples/with-supertokens), all protected routes load instantly. Would it be possible for me to try out your app / see the source code to help debug (even if you decide to use another provider)

> When I implement a check using getServerSideProps it loads almost instantly.

Using this or not, the verification should be instant anyway.

> Additionally it added 600 KB to my client bundle size, decided to go with another provider unfortunately.

Yea. This is a valid issue. Something we need to work on for sure. If you don't mind me asking, which provider did you decide to go with? :)

Thanks.

**Comment by henke443** [comment]
2-3 seconds was a bit of an exaggeration, its more like 1-1.5 seconds. 
![image](https://user-images.githubusercontent.com/2922864/128685372-f9729c45-afda-4127-b98e-4bdeee199642.png)
This is not the first page refresh and the example you provided with ```yarn build && yarn start```
This is still a little bit worse than for example the NextAuth example: https://next-auth-example.vercel.app/protected
![image](https://user-images.githubusercontent.com/2922864/128685516-e593705e-25cc-43b9-b601-0224e73bd5cb.png)

I'm considering using https://github.com/vvo/next-iron-session and making my own google integration but I'm unsure how wise this is. Thanks for your response also :) I really liked your API and everything else and I was very sad to switch.

**Comment by henke443** [comment]
I'm considering using next-iron and rolling my own google integration because that's the only provider I need, I'm unsure how wise this is or if its even faster though.

**Comment by henke443** [comment]
Nevermind I'm going to go with NextAuth, on my local machine the loading times are very good
![image](https://user-images.githubusercontent.com/2922864/128691221-7c11cd24-0a57-47ee-842b-7c6198ac9b36.png)

**Comment by rishabhpoddar** [comment]
I'm going to keep this issue open until we can fix the load time issue.. it shouldn't be happening for every page reload (just the first one, and not such high values either).

**Comment by rishabhpoddar** [comment]
So the issue here is related to the frontend checking if an email is verified or not in case email verification is required. If we switch off that config, then the load time is even more quick than NextAuth's since there is no API request needed to check if a session exists.

We will be working on changing how email verification works where we won't need to have this check on every page reload, thereby solving this issue even if email verification is switched on.

Closing this for now, thanks for pointing it out :)
