### ISSUE TITLE
Implement the Session recipeModule

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#18]
- [x] `import Session from "supertokens-node/recipe/session"`
- [x] Functions for these already exist in the package. They must be abstracted away into their own recipe module
- [x] Must follow its respective part from the [new FDI (v1.3.0)](https://github.com/supertokens/frontend-driver-interface/blob/master/v1.3.0.md) and [new CDI](https://github.com/supertokens/core-driver-interface/blob/master/v2.4.0.md)
- [x] The [init params](https://github.com/supertokens/supertokens-node/issues/18#issuecomment-710192935)

**Comment by rishabhpoddar** [comment]
## The init function for this Recipe:
```js
{
   accessTokenPath?: string,
   cookieSecure?: string,
   cookieSameSite?: string
}
```

**Comment by rishabhpoddar** [comment]
@NkxxkN , What are your thoughts on the name `Session.verifySession()`. This function will be used with any route that requires an active session. Like:
```
import Session from "supertokens-node/recipe/session";

app.post("/profile", Session.verify(), (req, res) => {
   let session = req.session;
   let userId = session.getUserId();
   // API Logic
})
```

**Comment by NkxxkN** [comment]
`verifySession` is good. I can also think of `isAuthenticated()` or `hasSession()`. Pick the one you prefer I think they all work.
