### ISSUE TITLE
Implement the EmailPassword recipeModule

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#19]
- `import EmailPassword from "supertokens-node/recipe/emailpassword"`
- All features in this module will have a default API implementation that uses functions provided by this library. These functions can be used by users to create their own API as well.
- The default APIs of all features must be able to be disabled via a `disableDefaultImplementation` `boolean` passed to them in their `init` function.
- Must follow its respective part from the [new FDI (v1.3.0)](https://github.com/supertokens/frontend-driver-interface/blob/master/v1.3.0.md) and [new CDI](https://github.com/supertokens/core-driver-interface/blob/master/v2.4.0.md)
-  Following are the sets of features:
   - [x] [signInFeature](https://github.com/supertokens/supertokens-node/issues/20)
   - [x] [signUpFeature](https://github.com/supertokens/supertokens-node/issues/21)
   - [x] [resetPasswordUsingTokenFeature](https://github.com/supertokens/supertokens-node/issues/22)
   - [x] [signOutFeature](https://github.com/supertokens/supertokens-node/issues/34)
- The `init` function of this module takes options as per the above features:
   ```js
   EmailPassword.init({
      signInFeature: {...},
      signUpFeature: {...},
      resetPasswordUsingTokenFeature: {...},
      signOutFeature: {...}
   })
   ```

**Comment by rishabhpoddar** [comment]
@NkxxkN ,
We need to allow users to create, verify and revoke their own session in an easy way

So I propose that we add another object in the config:
```
session?: {
   createNewSessionAndSendResponse?: (user: {id, email}, isFromSignUp: boolean, req, res) => void,
   verifySession?: (req, res) => Promise<string>, // string being userId
   revokeSessionAndSendResponse?: (req, res) => void
}
```

- By default, we will implement these assuming that they are using our session lib.
- We will need to communicate to them what `AndSendResponse` means. If they make a mistake and do not send the `id` and `email` in the response, the frontend can throw an error and log to send that information in the response, so that they can correct it.
- We will need a `logout` method on the frontend as well. I think it can be tied to the `emailpassword` recipe since sign in / logout are a function of auth first, and then a function of sessions (it's a part of auth, but implemented via sessions). How do you want to do this?

**Comment by NkxxkN** [comment]
> We will need a logout method on the frontend as well. I think it can be tied to the emailpassword recipe since sign in / logout are a function of auth first, and then a function of sessions (it's a part of auth, but implemented via sessions). How do you want to do this?

I agree that at first sight that it should be part of emailpassword since it is login related. In the future we will build other forms of login and they will share the logout method. Thinking like this, logout might be something that's implemented by `SuperTokens` recipe module manager directly?

> Should this interface actually be in the supertokens.init level? 

Agreed!

**Comment by rishabhpoddar** [comment]
> I agree that at first sight it should be part of emailpassword since it is login related. In the future we will build other forms of login and they will share the logout method. Thinking like this, logout might be something that's implemented by SuperTokens recipe module manager directly?

I think that logout should specific to each recipe as it's tightly coupled with how the login for that recipe works. Sure, many times it's going to have the same implementation, however, it's still semantically a function of that recipe (just like how signin is a function of a recipe)
