### ISSUE TITLE
 Type 'NextApiRequest' is missing the following properties error with version 8.4.0 (Nextjs 12.0.7)

### ISSUE THREAD

**Issue by habrigo** [supertokens/supertokens-node#240]
Using Nextjs 12.0.7 with supertokens-node 8.4.0 when build is launched getting the following stacktrace:

<pre>
./pages/api/auth/[[...path]].ts:23:26
Type error: Argument of type 'NextApiRequest' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
  Type 'NextApiRequest' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': get, header, accepts, acceptsCharsets, and 23 more.

  21 |   await superTokensNextWrapper(
  22 |     async (next) => {
23 |       await middleware()(req, res, next)
     |                          ^
  24 |     },
  25 |     req,
  26 |     res
error Command failed with exit code 1.
</pre>

**Comment by habrigo** [comment]
Followed the recommendation on the following stackoverflow page https://stackoverflow.com/questions/68536004/type-nextapirequest-is-missing-the-following-properties-from-type-requestpar

so I have replace the request and response with custom types as shown below:

<code>
type NextApiRequestCustom = NextApiRequest & Request;

type NextApiResponseCustom = NextApiResponse & Response;

supertokens.init(SuperTokensBackendConfig.backendConfig())

export default async function superTokens(
  req: NextApiRequestCustom,
  res: NextApiResponseCustom
</code>

Probably would be a better option to move the "type union" into the supertokens-node library.

Thanks.

**Comment by habrigo** [comment]
I can confirm it builds and works ok with using "type union" solution above.

**Comment by rishabhpoddar** [comment]
Thanks! The type union seems to be the best way to fix this. I would not want to move this into the lib though cause the `middleware` function being used is imported from the express framework, and so adding `NextApiRequestCustom` and `NextApiResponseCustom` to it's typing would not be correct.

Instead, I will update our docs to reflect this type union.

Do you have other ideas?

**Comment by habrigo** [comment]
@rishabhpoddar I think just updating documentation makes sense. I was about to update and create put a pull request but I just noticed you have already done this :) 

Thanks.
