### ISSUE TITLE
Optional: true not working for field validation

### ISSUE THREAD

**Issue by northloopfin** [supertokens/supertokens-node#241]
**Form fields in config:**

```signUpFeature: {
          formFields: [
            {
              id: "name",
              optional: false,
            },
            {
              id: "phone",
              optional: true,
            },
            {
              id: "address",
            },
            {
              id: "random_key"
            },
          ],
        }
```

**Working payload:**

```{
    "formFields": [
    {
        "id": "email",
        "value": "blah@123.com"
    },{
        "id": "password",
        "value": "1password1"
    },    
    {
        "id": "name",
        "value": "Random name"
    },
    {
        "id": "phone",
        "value": "+17777777777"
    },
    {
        "id": "address",
        "value": "random address"
    },
    {
        "id": "random_key",
        "value": "adasd"
    }
]
}
```

**Failing Payload:**

```
{
    "formFields": [
    {
        "id": "email",
        "value": "blah@123.com"
    },{
        "id": "password",
        "value": "1password1"
    },    
    {
        "id": "name",
        "value": "Random name"
    },
    {
        "id": "address",
        "value": "random address"
    },
    {
        "id": "random_key",
        "value": "adasd"
    }
]
}
```

**Error:** 

```
"message": "Are you sending too many / too few formFields?"
```

**Hypothesis:**

The following line in `/recipe/emailpassword/api/utils`

<img width="496" alt="image" src="https://user-images.githubusercontent.com/45414210/148819723-bfa0872c-d5e4-4860-bfb3-6d63e1c9a828.png">

Is causing the issue? It throws an error merely on the basis of difference in length of received input and defined formFields in the config.. without taking into account the `optional` property

**Comment by rishabhpoddar** [comment]
Hi,

In a form, if the field exists but the user has not entered any input in it (cause it's optional), will still send that id and value to the backend. The value in this case will be `""`.

Therefore, you need to pass in all the formFields, but the optional ones can be an empty string.

So try the API call with `{...}, {id: "phone", value: ""}, {...}]` and it will work.

Closing this comment for now, but feel free to reopen it.
