### ISSUE TITLE
"Bad Request" / "FST_ERR_CTP_EMPTY_JSON_BODY" error when enabling email verification with fastify

### ISSUE THREAD

**Issue by quinnfinite** [supertokens/supertokens-node#247]
I’m setting up email verification, and am a bit stuck. Log in and Sign up, works. But email verification does not send an email. 

The error logged in the console and network tab:

<img width="1313" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/6466480/150665814-d1cecf60-c619-4c12-be13-786a80211c71.png">

<img width="708" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/6466480/150665818-ff35655e-25a0-4da3-ae55-71647dbef004.png">

My front-end:

SuperTokens.init({
  appInfo: {
    appName: 'app',
    apiDomain: webAndApiDomain,
    websiteDomain: webAndApiDomain,
  },
  recipeList: [
    EmailPassword.init({
      emailVerificationFeature: {
        mode: 'REQUIRED',
      },
      palette: {
        primary: colors.turquoise,
      },
    }),
    Session.init(),
  ],
});

Back-end:

supertokens.init({
  framework: 'fastify',
  supertokens: {
    connectionURI: process.env.SUPER_TOKENS_CONNECTION_URI,
    apiKey: process.env.SUPER_TOKENS_API_KEY,
  },
  appInfo: {
    appName: 'app',
    apiDomain: webAndApiDomain,
    websiteDomain: webAndApiDomain,
  },
  recipeList: [
    EmailPassword.init(), // initializes signin / sign up features
    Session.init(), // initializes session features
  ],
});

From what I can tell, the issue has to do with Fastify's parser for application/json. [Fastify expects the request body to be a JSON object](https://github.com/fastify/fastify/issues/297#issuecomment-331800305) I noticed that if I create a custom parser that sets the request body to a stringified object when it's initially empty, the error ceases to throw. 

A temporary work-around for anyone with this issue could be to set a custom parser, ideally using [fastify's secure JSON parse](https://github.com/fastify/secure-json-parse#api). But that certainly isn't ideal.

**Comment by rishabhpoddar** [comment]
Whilst the custom parser can fix the issue, from a library point of view, we cannot add that since it would affect all other application's API as well.

Instead, the error is that the frontend SDK is sending the email verification token request with no JSON body but has content-type set to `application/json`. So adding an empty JSON body there would fix this issue.

**Comment by quinnfinite** [comment]
Agreed! I added that comment only as a temporary work around/evidence that sending no JSON body is the issue. Thank you for the fast response!

**Comment by rishabhpoddar** [comment]
I have released a new version of supertokens-auth-react (v0.18.3) that contains this fix. This is the associated [commit](https://github.com/supertokens/supertokens-auth-react/commit/74f0218c84977338b371c125a5fa8cf5dbeadaea).
