### ISSUE TITLE
Add additional attributes to the UserInfo

### ISSUE THREAD

**Issue by devkiran** [supertokens/supertokens-node#279]
Can we add the additional attributes to the UserInfo

```
UserInfo {
    id: string;
    email?: {
        id: string;
        isVerified: boolean;
    };
};
```

I'm trying to pass additional attributes to the front-end. On the front-end, I'm using the `useSessionContext` to get the user data.

```
const { userId, accessTokenPayload } = useSessionContext();
```

**Comment by rishabhpoddar** [comment]
You can add those attributes to the `accessTokenPayload` when creating a new session. And then they will be available to you on the frontend.

If you tell me the recipe you are using, I can point you to the docs.

**Comment by devkiran** [comment]
I'm using `supertokens-node/recipe/thirdpartyemailpassword`

**Comment by rishabhpoddar** [comment]
This is how you can add info to the access token payload: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/sessions/new-session

I'm closing this issue for now as it's not really a problem with the SDK. Please feel free to ask more questions about this on our [discord](https://supertokens.com/discord) though.
