### ISSUE TITLE
Third party apple login: can't change redirect URI

### ISSUE THREAD

**Issue by manu-urba** [supertokens/supertokens-node#295]
Hello there, I'll describe my scenario by saying this: I'm building a software that needs to authenticate three different types of users:
EndUsers, via phone application.
Planners, via phone application and web interface 1.
Admins, via web interface 2.
The recipe we are using is passwordless + social.

I work on the backend, which is built with NestJS. My coworkers are building the mobile app with React Native, both planner and admin web interfaces are build with ReactJS.

## Problem
Supertokens uses statically-defined URLs which are used as a `redirect_uri` query variable, and in order to change these dynamically I need to override the API. This is how I managed my issue with Google OAuth:
In order to let the devs choose the redirect URL for their app, I added a query param under `GET /auth/authorisationurl`:
![image](https://user-images.githubusercontent.com/39467342/165942146-59db9d8a-59ab-4bb8-8ef3-d4922dceb5ff.png)
(A) this URL is the query params the dev will change overriding the API, for example the planner web interface developer will override it to `https://evt-client-planner-dev.revod.cloud/auth/login/callback/google`, the mobile developer will change it to `https://evt-api-dev.revod.cloud/redirect/{encodeURIcomponent(finalURL)}` <-- this URL is handled by my API, which redirects the user to the final destination (for mobile app it will be `custom-protocol://callback/google?code=...`)

This is how I implemented this feature:
```ts
authorisationUrlGET: async function (input: {
  provider: TypeProvider;
  options: ThirdPartyAPIOptions;
  userContext: any;
}): Promise<{
  status: 'OK';
  url: string;
}> {
  const response =
    await originalImplementation.authorisationUrlGET(input);
  if (response.status != 'OK') return response;
  if (
    input.provider.id == 'google' ||
    input.provider.id == 'apple'
  ) {
    const urlWithRedirect = new URL(response.url);
    if (input.options.req.original.query.redirect_uri) {
      urlWithRedirect.searchParams.delete('redirect_uri');
      urlWithRedirect.searchParams.append(
        'redirect_uri',
        input.options.req.original.query.redirect_uri,
      );
    }
    return {
      status: 'OK',
      url: urlWithRedirect.toString(),
    };
  }
},
```
---
This approach works just fine, however **I can't really do this with apple**.
I'll show you the steps trying to reproduce:

I generate a consent URL with a custom `redirect_uri`, see code above
![image](https://user-images.githubusercontent.com/39467342/165944043-5cdea81d-9118-4862-9dde-a52cf09dee49.png)

I authenticate with my apple ID keeping my chrome network tab open
![image](https://user-images.githubusercontent.com/39467342/165944252-0e496355-283c-4490-b3f1-31c05c3dfaa9.png)

I get correctly redirected to the `redirect_uri`
![image](https://user-images.githubusercontent.com/39467342/165944590-1ec195b0-fcbd-489d-8419-15b8d45d6dd4.png)
(A) the errors are normal, I'm still not handling the request in the API.
(B) as you can see from the URL and from here, apple redirects me to `https://evt-api-dev.revod.cloud/redirect` performing a POST request

The body of the request contains the `code`
![image](https://user-images.githubusercontent.com/39467342/165944961-de567080-95cb-4b51-9ba7-de3dbb01fd10.png)

I `POST` the code to `auth/signinup`
![image](https://user-images.githubusercontent.com/39467342/165945187-a73c7e7e-840d-4f38-ba1b-be7059496a4a.png)

As you can see it throws an error, so I debugged it and here's what it says
![image](https://user-images.githubusercontent.com/39467342/165946009-e1c2044d-2128-4ea9-8616-366ed50a7baa.png)
(A) It looks like it **expects** the `redirect_uri` to be `https://evt-api-dev.revod.cloud/auth/callback/apple`.

## Potential solution I came up with
I will make the user insert an additional parameter in this request
![image](https://user-images.githubusercontent.com/39467342/165946321-602d0a54-7fbd-4ca4-9da3-f85e677a8904.png)
So, overriding `appleRedirectHandlerPOST` I can read that parameter from the express request and I replace the html script url with that one.
```ts
appleRedirectHandlerPOST: async function (input) {
  return __awaiter(this, void 0, void 0, function* () {
    const redirectURL =
      input.options.appInfo.websiteDomain.getAsStringDangerous() +
      input.options.appInfo.websiteBasePath.getAsStringDangerous() +
      '/callback/apple?state=' +
      input.state +
      '&code=' +
      input.code;
    input.options.res.sendHTMLResponse(
      `<html><head><script>window.location.replace("${redirectURL}");</script></head></html>`, // Here, I replace redirectURL with actualRedirectURI which can be found under input.options.req.original.query.actualRedirectURI
    );
  });
},
```

What do you think about this approach? Will there be a better solution to change redirect URIs with supertokens?

---

See [original discussion on discord](https://discord.com/channels/603466164219281420/969484740866490409/969484747870982224).

**Comment by rishabhpoddar** [comment]
Thanks for the detailed issue description. There is clearly a need for a better API interface here. I'll get back to this issue in a few days.

**Comment by rishabhpoddar** [comment]
This is also related to https://github.com/supertokens/supertokens-node/issues/218

**Comment by rishabhpoddar** [comment]
Specific to the problem described in this issue, it can be solved by setting the default apple provider implement's [`getRedirectURI` function](https://github.com/supertokens/supertokens-node/blob/master/lib/ts/recipe/thirdparty/providers/apple.ts#L140) to `undefined`, something like this:
```ts
let apple = Apple({...});

let providers = [
    {
        ...apple,
        get: async function (redirectURI: string | undefined, authCodeFromRequest: string | undefined, userContext: any) {
            let getResponse = apple.get(redirectURI, authCodeFromRequest, userContext);
            return {
                ...getResponse,
                getRedirectURI: undefined
            }
        }
    }
]
```

This way, the flow for redirect_uri that is sent to apple during exchanging the auth code for the access token is the same as what is sent in the request to the signinup API call (just like how it works for google).

I'm closing this issue for now, but feel free to reopen if required.
