### ISSUE TITLE
Sign out leaves zombie session after deleting user

### ISSUE THREAD

**Issue by danieldunderfelt** [supertokens/supertokens-node#343]
I am doing a delete user feature, but after I delete the user and sign out, I cannot access the /auth path again as there seems to be some kind of session still alive.

Normal logging out without deleting the user works.

Attached are frontend and backend logs.

[be_logs.txt](https://github.com/supertokens/supertokens-node/files/9045017/be_logs.txt)

[fe_logs.txt](https://github.com/supertokens/supertokens-node/files/9045022/fe_logs.txt)

**Comment by rishabhpoddar** [comment]
Until this is fixed, a workaround is to override the signOutPOST API function in the Session.init as follows:
```ts
Session.init({
    override: {
        apis: (oI) => {
            return {
                ...oI,
                signOutPOST: async function (input) {
                    let resp = await oI.signOutPOST!(input);
                    if (resp.status === "OK") {
                        throw new Session.Error({
                            message: "Sign out",
                            type: "UNAUTHORISED",
                        })
                    }
                    return resp;
                }
            }
        }
    }
})
```

**Comment by danieldunderfelt** [comment]
> Until this is fixed, a workaround is to override the signOutPOST API function in the Session.init as follows:
> 
> ```ts
> Session.init({
>     override: {
>         apis: (oI) => {
>             return {
>                 ...oI,
>                 signOutPOST: async function (input) {
>                     let resp = await oI.signOutPOST!(input);
>                     if (resp.status === "OK") {
>                         throw new Session.Error({
>                             message: "Sign out",
>                             type: "UNAUTHORISED",
>                         })
>                     }
>                     return resp;
>                 }
>             }
>         }
>     }
> })
> ```

I confirm this works in my app.
