### ISSUE TITLE
NestJS 8 + express 4 error while setting header with key: front-token and value

### ISSUE THREAD

**Issue by cfh-se** [supertokens/supertokens-node#346]
After being logged in for a while and making a request to my backend (NestJS 8 and express 4) I get the following error:

[Nest] 78  - 07/05/2022, 9:56:51 AM   ERROR [ExceptionsHandler] Error while setting header with key: front-token and value: eyJ1aWQiOiJkYjZmYWVlNC0zNDU1LTRlYTYtODdjOS04N2M2NjA4MzA0YWYiLCJhdGUiOjE2NTcwMTg2MTExNTEsInVwIjp7InJvbGUiOiJBRE1JTiIsIm9yZ2FuaXphdGlvbklkIjoidGVzdCJ9fQ==
rapid-api_1    | Error: Error while setting header with key: front-token and value: eyJ1aWQiOiJkYjZmYWVlNC0zNDU1LTRlYTYtODdjOS04N2M2NjA4MzA0YWYiLCJhdGUiOjE2NTcwMTg2MTExNTEsInVwIjp7InJvbGUiOiJBRE1JTiIsIm9yZ2FuaXphdGlvbklkIjoidGVzdCJ9fQ==
rapid-api_1    |     at Object.setHeaderForExpressLikeResponse (/usr/src/app/node_modules/supertokens-node/lib/build/framework/utils.js:236:15)
rapid-api_1    |     at ExpressResponse.setHeader (/usr/src/app/node_modules/supertokens-node/lib/build/framework/express/framework.js:111:21)
rapid-api_1    |     at Object.setFrontTokenInHeaders (/usr/src/app/node_modules/supertokens-node/lib/build/recipe/session/cookieAndHeaders.js:73:9)
rapid-api_1    |     at Object.<anonymous> (/usr/src/app/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:216:44)
rapid-api_1    |     at Generator.next (<anonymous>)
rapid-api_1    |     at fulfilled (/usr/src/app/node_modules/supertokens-node/lib/build/recipe/session/recipeImplementation.js:15:36)
rapid-api_1    |     at processTicksAndRejections (node:internal/process/task_queues:95:5)

It seems to originate from node_modules/supertokens-node/lib/build/framework/utils.js:236:15 where a "TypeError: res.getHeaders is not a function" is thrown.

I have followed the NestJS guide and tried to disable all other filters, exceptions but the error still occurs now and then.

``
{
"dependencies": {
    "@google-cloud/storage": "^5.19.3",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^2.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-ws": "^8.4.5",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/terminus": "^8.0.6",
    "@nestjs/typeorm": "^8.1.4",
    "@nestjs/websockets": "^8.4.5",
    "@redis/client": "^1.1.0",
    "axios": "^0.26.1",
    "cache-manager": "^3.6.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "compression": "^1.7.4",
    "handlebars": "^4.7.7",
    "helmet": "^5.0.2",
    "joi": "^17.6.0",
    "meilisearch": "^0.25.0",
    "mysql2": "^2.3.3",
    "nodemailer": "^6.7.3",
    "rapid-client": "^1.0.91",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "supertokens-node": "^9.2.0",
    "swagger-ui-express": "^4.3.0",
    "typeorm": "^0.3.7",
    "uuid": "^8.3.2"
  }
}
``

**Comment by rishabhpoddar** [comment]
Closing this issue since there was an issue with using `ctx.getRequest()` instead of using `ctx.getResponse()`
