### ISSUE TITLE
Call SuperTokens API to send the password reset email

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#38]
The API will take the following as an input:
- email (string)
- App name (string)
- Password reset URL (string)

- It will send an email to `email` containing the App name and the Password reset URL.
- The design of the password reset email is [here](https://github.com/supertokens/supertokens-auth-react/issues/10#issuecomment-710364772).
- Throw a 400 error when:
   - Email is syntactically bad
   - app name is ""
   - the password reset URL is an invalid URL
- We also need a way to monitor how many emails are being sent so that our domain does not get blacklisted (in the bad case)
- The email subject will be "Reset your password"
- The email will be sent via: "no-reply@supertokens.io"
- The name of the sender should be the same as the App name
- The API should return and THEN sends the email.

----------
In the SDK side, follow: https://github.com/supertokens/supertokens-node/issues/44#issuecomment-722947808

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya please come up with an API spec for the above. It should be a `POST` API.

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya the API should return and THEN sends the email.

**Comment by bhumilsarvaiya** [comment]
**API Endpoint**: `/0/st/auth/password/reset`
**Method**: `POST`
**Success Response**: `{}`
**Success Response Code**: `200`
**Possible Response Codes**: `200, 400, 408, 500`
**Required in Request**:
- headers:
    - api-version: 0
- request-body:
   ```
   {
       email: string,
       appName: string,
       passwordResetURL: string
   }
   ```

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya the following changes to the password reset email:

- "A password reset request for your account on <app name> has been received. Please click on the button below to continue further" -> "A password reset request for your account on <app name> has been received."

- Center align the above text

**Comment by rishabhpoddar** [comment]
The email does not seem render well on iOS devices
![Image from iOS](https://user-images.githubusercontent.com/2976287/98366244-a194e500-2059-11eb-8327-2b7d39d1cb70.png)
