### ISSUE TITLE
Issues with the guide

### ISSUE THREAD

**Issue by mengnans** [supertokens/supertokens-node#381]
From this guide https://supertokens.com/docs/emailpassword/nestjs/guide
```
import { ExceptionFilter, Catch, ArgumentsHost } from '@nestjs/common';
import { Request, Response, NextFunction, ErrorRequestHandler } from 'express';

import { errorHandler } from 'supertokens-node/framework/express';
import { Error as STError } from 'supertokens-node';

@Catch(STError)
export class SupertokensExceptionFilter implements ExceptionFilter {
  handler: ErrorRequestHandler;

  constructor() {
    this.handler = errorHandler();
  }

  catch(exception: Error, host: ArgumentsHost) {
    const ctx = host.switchToHttp();

    const resp = ctx.getResponse<Response>();
    if (resp.headersSent) {
      return;
    }

    this.handler(
      exception,
      ctx.getRequest<Request>(),
      resp,
      ctx.getNext<NextFunction>(),
    );
  }
}
```
The constructor `this.handler = errorHandler();`
Isn't errorHandler() returns a promise?
Eslint is screaming with `@typescript-eslint/no-misused-promises` error.

Thanks in advance.

**Comment by rishabhpoddar** [comment]
`errorHandler` returns an async function: https://github.com/supertokens/supertokens-node/blob/master/lib/ts/framework/express/framework.ts#L177

**Comment by mengnans** [comment]
@rishabhpoddar it is `Promise<void>` from index.d.ts

![image](https://user-images.githubusercontent.com/20500503/188528963-719f3bb8-0f82-4479-8aee-7d12923da2af.png)

**Comment by mengnans** [comment]
This is the error I got

**Comment by mengnans** [comment]
Maybe I should just turn it off

```
rules: {
    {
      "@typescript-eslint/no-misused-promises": [
        "error",
        {
          "checksVoidReturn": false
        }
      ]
    }
}
```

**Comment by rishabhpoddar** [comment]
This is the type in index.d.ts: https://github.com/supertokens/supertokens-node/blob/master/lib/build/framework/express/index.d.ts#L8

It returns a function which returns `Promise<void>` which is correct.

**Comment by mengnans** [comment]
Thanks @rishabhpoddar, I believe this is related to https://github.com/typescript-eslint/typescript-eslint/issues/2979.
As no-misused-promises doesn't like `Promise<void>`.
I am closing the issue as I don't think it's a supertokens' issue.
