### ISSUE TITLE
Error raised by Session.getSession is serialized to `[object Object]`

### ISSUE THREAD

**Issue by n1ru4l** [supertokens/supertokens-node#382]
An error thrown/rejected by the Promise returned from `Session.getSession` seems to be stringified to `[object Object]` instead of `[Error: message]`, which makes it hard to debug (Does it correctly extend the Error class?).

It seems like it is no real Error instance, when manually logging such an error we see the following:

```
SessionError {
  type: 'TRY_REFRESH_TOKEN',
  message: 'Access token has expired. Please call the refresh API',
  payload: undefined,
  errMagic: 'ndskajfasndlfkj435234krjdsa',
  fromRecipe: 'session'
}
```

We narrowed the issue down in this PR: https://github.com/kamilkisiela/graphql-hive/commit/63e66ab48335a3173d870c07a9510734b7f3c4af

**Comment by rishabhpoddar** [comment]
Fixed in version >= 12.0
