### ISSUE TITLE
Deleting session from custom mysql database has no effect

### ISSUE THREAD

**Issue by dvalley56** [supertokens/supertokens-node#400]
I am using `angular universal` as an mvc mainly for authentication for my subdomains and since it uses ssr i can't use `supertokens-auth-react` and `supertokens-web-js`. So I am using api for authentication and it is working well as of now (currently implemented signin, signup and signout).

I was just curious about **session management**, what I did was
```
1. Created User
2. Signed In with that user (session was created in session_info)
3. I manually deleted session from DB
```

But my auth flow was still going well (`verifySession()` and also `ThirdPartyEmailPassword.getUserById(userId)` working). 
I also tried restarting my angular app and also supertoken core, but auth was still working (not a single row of session_info).

After signing out manually, I was signed out properly.

My question is am I correct thinking that deleting session from db should logout the user using that session ? or if I am wrong, please correct me.

**Comment by rishabhpoddar** [comment]
Hey! 

Session verification is starless on the backend. This means it doesn't query the db (cause we optimise for speed). 

Once the session's access token expires, our frontend SDK will attempt to refresh it. The refresh api does query the db, which would then fail - logging out the user.

**Comment by dvalley56** [comment]
> Hey!
> 
> Session verification is starless on the backend. This means it doesn't query the db (cause we optimise for speed).
> 
> Once the session's access token expires, our frontend SDK will attempt to refresh it. The refresh api does query the db, which would then fail - logging out the user.

Ohh Thats nice
We also have function to revoke all the session for the user.  JUST AWESOME!!

And thanks for quick response.


One more thing was bothering me, in your react UI SDK on reload how does it knows that a valid session (cookie) is there as I cannot see anything in the network tab (session/refresh).

**Comment by rishabhpoddar** [comment]
> One more thing was bothering me, in your react UI SDK on reload how does it knows that a valid session (cookie) is there as I cannot see anything in the network tab (session/refresh).

On session creation, we store some information in the frontend cookies (sIdRefreshToken) - if this is there and its value != `"remove"`, it means that a session exists.

So our frontend SDK just reads this token from the browser cookie.

I am closing this issue since it's not really an issue. But feel free to reopen if you have more questions.
