### ISSUE TITLE
Unable to add additional form field during signup

### ISSUE THREAD

**Issue by Carder07** [supertokens/supertokens-node#405]
##Are you sending too many / too few formFields? 

### current frontend configuration

<sup>
signInAndUpFeature: {

                signUpForm: {

                    formFeilds: [{

                        id: "firstName",
                        optional: true

                    }, {

                        id: "lastName",
                        optional: true

                    }, {

                        id: "mobileContact",
                        optional: true

                    }]
                }
            }

 current backend configuration

 signUpFeature: {

                formFeilds: [{

                    id: "firstName",
                    optional: true

                }, {
                    id: "lastName",
                    optional: true

                }, {
                    id: "mobileContact",
                    optional: true

                }]

            }

</sup>

server response

{"message":"Are you sending too many / too few formFields?"}

**Comment by nkshah2** [comment]
Hi @Carder07,

We need a little more information to debug this properly, what frontend and backend SDK are you using? Also are you using the frontend SDK as an npm import or a plan HTML script tag?

**Comment by Carder07** [comment]
-On the frontend am using the supertokens-web-js imported with script tags.
-On the backend am using the node SDK together with express .

**Comment by nkshah2** [comment]
Thanks, so I tested it out with the following config

## Frontend config

```html
<script src="https://cdn.jsdelivr.net/gh/supertokens/supertokens-web-js/bundle/website.js"></script>
<script src="https://cdn.jsdelivr.net/gh/supertokens/supertokens-web-js/bundle/supertokens.js"></script>
<script src="https://cdn.jsdelivr.net/gh/supertokens/supertokens-web-js/bundle/session.js"></script>
<script src="https://cdn.jsdelivr.net/gh/supertokens/supertokens-web-js/bundle/emailpassword.js"></script>
```

```ts
supertokens.init({
    appInfo: {
        appName: "SuperTokens Demo App",
        apiDomain: "http://localhost:3001",
        websiteDomain: "http://localhost:3000",
    },
    recipeList: [
        supertokensEmailPassword.init(),
        supertokensSession.init(),
    ],
})
```
## Backend config

```bash
npm i supertokens-node
```

```ts
supertokens.init({
    supertokens: {
        connectionURI: "https://try.supertokens.com",
    },
    appInfo: {
        appName: "SuperTokens Demo App",
        apiDomain: "http://localhost:3001",
        websiteDomain: "http://localhost:3000",
    },
    recipeList: [
        EmailPassword.init({
            signUpFeature: {
                formFields: [
                    {
                        id: "firstName",
                        optional: true,
                    },
                    {
                        id: "lastName",
                        optional: true,
                    },
                    {
                        id: "mobileContact",
                        optional: true,
                    }
                ],
            },
        }), 
        Session.init(),
    ],
})
```

When I call the sign up API with 

```ts
let response = await supertokensEmailPassword.signUp({
            formFields: [
                {
                    id: "email",
                    value: "<EMAIL>",
                },
                {
                    id: "password",
                    value: "...",
                },
                {
                    id: "firstName",
                    value: "...",
                },
                {
                    id: "lastName",
                    value: "...",
                },
                {
                    id: "mobileContact",
                    value: "...",
                },
            ],
        });
```

It works correctly. Can you post the full configuration (including import statements) you pass to SuperTokens.init on the frontend and backend?

**Comment by Carder07** [comment]
Both configuration are all the same , the kept me wondering , to i compared both configuration and spotted the error in my code. it originates from the spelling of "formFields" on the backend. Thanks a lot. More power to your elbow.
