### ISSUE TITLE
Supertokens sometimes prevents tests from finishing

### ISSUE THREAD

**Issue by morgante** [supertokens/supertokens-node#410]
Supertokens will occasionally cause my Jest tests (server-side) to fail because it leaves open file handlers during the init call.

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TLSWRAP

      488 |       return;
      489 |     }
    > 490 |     SuperTokens.init({
          |                 ^
      491 |       framework: 'fastify',
      492 |       supertokens: {
```

is there something I can do in an `afterAll` hook to wait for Supertokens to either finish init or shutdown?

**Comment by bhumilsarvaiya** [comment]
Hey @morgante, can you share few of the tests for which you're getting this error. If you prefer, we can get on a call and resolve this for your. Let us know

**Comment by morgante** [comment]
The tests are very basic (using Jest). I don't think the contents matter:

```
describe('Auth service', () => {
  let user: TestUser;

  beforeAll(async () => {
    user = await createTestUser(TestUserType.Random);
  });

  afterAll(async () => {
    await user.clean();
  });

  // Test if a user gets roles through access to a project
  it('should get roles for a user', async () => {
    // First confirm user does not have any roles
    const roles = await user.account.getRoles();
    expect(roles.length).toBe(0);
  });
});
```

I'm `veritas` on Discord if you want to chat there.

**Comment by bhumilsarvaiya** [comment]
Hey @morgante, I've pinged you on discord

**Comment by rishabhpoddar** [comment]
@morgante we could get on a debugging call for this - it would help close this issue quickly. You can pick a time you like here: https://supertokens.com/call-user

thanks

**Comment by rishabhpoddar** [comment]
The issue was that telemetry was enabled from the SDK side whose request took longer to complete than the test itself leaving a background "job" running. Disabling telemetry like this, solved the issue:
```ts
import supertokens from "supertokens-node";

supertokens.init({
   disableTelemetry: true,
   //...
})
```
