### ISSUE TITLE
Recommended way to enforce email uniqueness

### ISSUE THREAD

**Issue by steliosrousoglou** [supertokens/supertokens-node#436]
I'm using the ThirdPartyEmailPassword recipe, and looking for a way to enforce email uniqueness across all signup/signin methods, i.e. no user can sign up with their email with more than one methods, be it email/password or third party.

Is there a configuration-level fix to this (I am using a self-hosted instance) or do I need to enforce it on the database level and surface the error manually? Is there a recommended approach for either?

Any insights much appreciated, thanks!

**Comment by rishabhpoddar** [comment]
Hey @steliosrousoglou you can add this feature via backend overrides like so:
```tsx
ThirdPartyEmailPassword.init({
    override: {
        apis: (oI) => {
            return {
                ...oI,
                thirdPartySignInUpPOST: async function (input) {
                    try {
                        return await oI.thirdPartySignInUpPOST!(input);
                    } catch (err) {
                        if (err.message === "Cannot sign up as email already exists") {
                            return {
                                status: "GENERAL_ERROR",
                                message: "Seems like you already have an account with email password or another social login. Use that instead."
                            }
                        }
                        throw err;
                    }
                }
            }
        },
        functions: (oI) => {
            return {
                ...oI,
                emailPasswordSignUp: async function (input) {
                    let existingUser = await ThirdPartyEmailPassword.getUsersByEmail(input.email);
                    if (existingUser.length === 0) {
                        return oI.emailPasswordSignUp(input);
                    }
                    return {
                        status: "EMAIL_ALREADY_EXISTS_ERROR"
                    };
                },
                thirdPartySignInUp: async function (input) {
                    let existingUser = await ThirdPartyEmailPassword.getUsersByEmail(input.email);
                    if (existingUser.length === 0) {
                        return oI.thirdPartySignInUp(input);
                    }
                    if (existingUser.find(i => i.thirdParty !== undefined && i.id === input.thirdPartyId)) {
                        // this means we are trying to sign in with the same social login now. So we allow it
                        return oI.thirdPartySignInUp(input);
                    }
                    throw new Error("Cannot sign up as email already exists");
                }
            }
        }
    }
})
```

To sum up the overrides, we check during email password sign up and thirdparty sign in up functions that if the user user's email already exists and if it does, we return the appropriate error message to the frontend.

In case of email password, we already have a status that we can used called `EMAIL_ALREADY_EXISTS_ERROR` which will send the right API response and display the right message on the frontend (for pre built UI)

In case of social login sign in up, we have no such status code, so we throw an error in the function level and then catch that in the API functions to return a [general error message](https://supertokens.com/docs/thirdpartyemailpassword/advanced-customizations/apis-override/custom-response/general-error) to the frontend which is then displayed to the user (for pre built UI).

Hope this helps. I am closing this issue for now, but feel free to reopen is if required.

**Comment by steliosrousoglou** [comment]
@rishabhpoddar Thanks, works like a charm!

For anyone else reading, the only small bug I found was 

`if (existingUser.find(i => i.thirdParty !== undefined && i.id === input.thirdPartyId)) {`

where the last comparison should instead be

`i.thirdParty.id === input.thirdPartyId`

**Comment by rishabhpoddar** [comment]
oh yea @steliosrousoglou thanks for pointing this out. I have edited my comment above to reflect the same

**Comment by rishabhpoddar** [comment]
For anyone else who sees this, we have now added docs for this in our recipe guides: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/deduplication/implementing-deduplication
