### ISSUE TITLE
Installation Netlify react

### ISSUE THREAD

**Issue by ticaboo** [supertokens/supertokens-node#437]
Follow up from call with @rishabhpoddar  - many thanks, super awesome dude.
 
Nearly there :)
 code:
https://github.com/timermachine/timermachine-frontend-auth
https://github.com/timermachine/timermachine-netlify-app

frontend deployed to https://timermachine.com/member
netlify deployed to https://app.timermachine.com/member

I think at point getting 404 on site, while postman /curl to netlify gives {"message":"unauthorised"}% 

please advise.
thx - Henry

**Comment by rishabhpoddar** [comment]
Closing this issue since we updated the docs (see linked PR)
