### ISSUE TITLE
Behaviour for sending password reset emails.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#44]
@NkxxkN your thoughts on the below please:
- On the backend, if there is any error, we simply ignore it and send an OK to the client. Is this OK?
   - I think it's OK
- On the frontend, the user can send another password reset email?
   - I think this is OK as long as there is some sort of a rate limiting (maybe not for MVP, but later). This will have to be done on the frontend and backend side.
- Based on the above, the API should send the email AFTER sending a reply to the client. This way, from a user's point of view, the UI is "quick". However, there would be a fake delay added in the API for security reasons and cause there is generally some sort of delay that is expected by the user anyway.

**Comment by NkxxkN** [comment]
> On the backend, if there is any error, we simply ignore it and send an OK to the client. Is this OK?

If the error is that the email does not exist we should return "OK". If the error is anything else related to our infrastructure or anything, it would be better to return a `GENERAL_ERROR`, not letting the users refreshing their emails and get frustrated.

> I think this is OK as long as there is some sort of a rate limiting (maybe not for MVP, but later). This will have to be done on the frontend and backend side.

Currently, in the frontend, to send a new email for reset password means you need to type your email again. This is for two reasons: we make sure that if the email is incorrect the user repeats the process to correct it, and this is also a natural front end rate limiting. 

Agreed that we will need a rate limiting in the backend regardless.

> Based on the above, the API should send the email AFTER sending a reply to the client. This way, from a user's point of view, the UI is "quick". However, there would be a fake delay added in the API for security reasons and cause there is generally some sort of delay that is expected by the user anyway.

I suppose we are talking about a queueing system (such as AWS SQS), I think this is the right approach.

> there would be a fake delay added in the API for security reasons

How is delaying the email delivery adding security?

**Comment by rishabhpoddar** [comment]
> Currently, in the frontend, to send a new email for reset password means you need to type your email again. This is for two reasons: we make sure that if the email is incorrect the user repeats the process to correct it, and this is also a natural front end rate limiting.

Are you sure this is a good behaviour? The user is anyway annoyed that they need to go through this flow. To that, we are adding more friction.. Isn't there a better way to rate limit? Like to disable the reset password email button for 5 seconds after it's used.

> How is delaying the email delivery adding security?

The time for the API should be the same in case the email exists or not. That's why, we need to delay in the case if the email exists and we are sending the email asynchronously. If we are sending the email async, then there is no way to communicate any error back to the user (which ties in with your first point). I am OK with that

**Comment by rishabhpoddar** [comment]
To conclude:
- We will send the email async
- We will ignore all errors when sending the email
- We will add some delay in the API in case the email is found (same as if the email is not found)

**Comment by NkxxkN** [comment]
> Are you sure this is a good behaviour? The user is anyway annoyed that they need to go through this flow. To that, we are adding more friction.. Isn't there a better way to rate limit? 

I don't think it's actually important as a regular user will quit the page after they have sent the email because they consider it done. If the email didn't come in the next 15mins, that's when they get annoyed, come back and try again. 
This is a bad design only if the user wants to abuse our system which I'm fine with.

> To conclude:
> We will send the email async
> We will ignore all errors when sending the email
> We will add some delay in the API in case the email is found (same as if the email is not found)

Why do we need to add any delays at all if we are sending the email async? 
Or if we want to add a random delay it should be a small delay as the time difference between the two cases is very small, so no need to add a huge delay.

**Comment by rishabhpoddar** [comment]
> I don't think it's actually important as a regular user will quit the page after they have sent the email because they consider it done. If the email didn't come in the next 15mins, that's when they get annoyed, come back and try again.
This is a bad design only if the user wants to abuse our system which I'm fine with.

Okay. We can keep it how it is

> Why do we need to add any delays at all if we are sending the email async?
Or if we want to add a random delay it should be a small delay as the time difference between the two cases is very small, so no need to add a huge delay.

Yea.. makes sense. No delay at all then, for any purpose
