### ISSUE TITLE
Dashboard Verification request 400 bad request due to missing application/json body

### ISSUE THREAD

**Issue by jztochigami** [supertokens/supertokens-node#454]
It seems that the validation request that supertokens-dashboard sends doesn't contain a application/json body, thus causing the request to error out.
![image](https://user-images.githubusercontent.com/118142357/206133054-b7419997-8ae5-4a7d-82db-fb72533943cb.png)

**Comment by nkshah2** [comment]
Closing this in favor of https://github.com/supertokens/dashboard/issues/59
