### ISSUE TITLE
supertokens node security (12.1.3)

### ISSUE THREAD

**Issue by Chunkygoo** [supertokens/supertokens-node#461]
jsonwebtoken  <=8.5.1
Severity: high
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
jsonwebtoken has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q
fix available via `npm audit fix --force`
Will install supertokens-node@2.2.2, which is a breaking change
node_modules/jsonwebtoken
  supertokens-node  >=2.3.0
  Depends on vulnerable versions of jsonwebtoken
  Depends on vulnerable versions of twilio
  Depends on vulnerable versions of verify-apple-id-token
  node_modules/supertokens-node
  twilio  >=2.6.0
  Depends on vulnerable versions of jsonwebtoken
  node_modules/twilio
  verify-apple-id-token  *
  Depends on vulnerable versions of jsonwebtoken
  node_modules/verify-apple-id-token

4 vulnerabilities (3 moderate, 1 high)

**Comment by rishabhpoddar** [comment]
The fix to this involves updating jsonwebtoken to 9.0.0 which doesn't support versions of node below 11. This would have been fine, except that we are not using the verify function from jsonwebtoken package.

**Comment by rishabhpoddar** [comment]
We decided to fix this anyway since node 11 is quite old at this point. This has been fixed in supertokens-node version >= 12.1.6
