### ISSUE TITLE
Header Access-Control-Allow-Origin should allow '*' value

### ISSUE THREAD

**Issue by montedonioluiz** [supertokens/supertokens-node#462]
Hi there!

My company's system requires a multi-tenancy implementation, and each of our clients will have their own specific front-end address with the Supertokens frontend implemented via proxy with their own url (www.client1.com, www.client2.com etc), however our backend code will be in a single server with a single URL and serve all web calls. This is creating a massive problem with the Supertokens CORS config because it apparently does not allow the value for the Access-Control-Allow-Origin response header to be `*`, and in our case it must be. 

I've even found a troubleshooting page stating that some errors related to CORS, which are the ones I've been getting, are because this header is set to `*`, and it instructs us to pass in the origin we would call the service from: https://supertokens.com/docs/passwordless/troubleshooting/cors-issues#error-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-is-true

I've recently opened a thread on the Discord chanel about this as well: https://discord.com/channels/603466164219281420/1055635627384770600

Is it possible to implement the wildcard?

**Comment by rishabhpoddar** [comment]
Hey @montedonioluiz using wildcard won't work cause browsers don't allow that when using secure cookies.

So that best way to solve this problem is to dynamically assign the `origin` array like shown here: https://www.npmjs.com/package/cors#configuring-cors-w-dynamic-origin.

This way, you can keep the list of tenants sub domain in your db and read from there.

I'm closing this issue since there is nothing that can be done from SuperTokens side here given that it's a browser rule.

**Comment by montedonioluiz** [comment]
Hey there @rishabhpoddar, thanks for the feedback!

Our back-end stack is Node.js w/ AWS lambda, so there are two places where we must deal with cors: our API gateway definition and our lambda handler declaration. Using the example found at [supertokens-auth-react](https://github.com/supertokens/supertokens-auth-react/blob/master/examples/with-aws-lambda/backend/auth.js), we were able to setup with any origins, usgin the getOrigin function from the `middy/http-cors` lib. 

The problem we currently have is in our gateway definition. We cannot dynamically fetch the list of our tenants' domains because AWS's API gateway is deployed statically; you cannot insert (I don't think, at least) logic to determine specific values for headers on demand or by each request. We can have middleware/authorizer functions, however even that would only be after bypassing the first layer of the gateway, which is exactly where the CORS definition for the allowed origins must be pre-set. 

Also, the reason we cannot statically declare the allowed origins as a pre-defined list in the gateway is because our tenant creation is dynamic; we have a tenants API that can be accessed to create a new tenant at any point in time, and it would not be very efficient to manually or even automatically upload the tenant list in the gateway and then force a re-deploy.

**Comment by rishabhpoddar** [comment]
hey @montedonioluiz did the using lambda for OPTIONS method work?

**Comment by montedonioluiz** [comment]
Hey @rishabhpoddar sorry about the delay, we've been busy working on the implementation.

So your proposal to dynamically set the value of the `Access-Control-Allow-Origin` header by creating the OPTIONS path as a lambda-proxy-integration in our API Gateway worked, however we quickly realized that this will not scale efficiently. If we only have one lambda to handle the OPTIONS calls, all of our services would access it during runtime (we have over 150 functions in production today) so that would rise the costs of our infrastructure pretty quickly.

By researching some more and asking a couple of our devs to take a bigger look into this problem, we were finally able to come up with a viable solution:

We create an OPTIONS method for each route in our API Gateway and through the `x-amazon-apigateway-integration/responses/default/responseTemplates` field we can access the current origin of the request and override the header there. This took quite a while to figure out and the AWS docs didn't help much... for example weren't even sure of what language/syntax/pattern is used in this `$.context`. One of our devs just happened to have worked with Apache Velocity in the past and recognized the syntax. We're still not sure if this really is what is being used by AWS hahah but the proposed logic is working now
```yaml
paths:
  /signinup/code:
    post:
      summary: Enviar OTP ao usuário
      x-amazon-apigateway-request-validator: Validate body, query string parameters, and headers
      x-amazon-apigateway-integration:
        uri: lambda-arn
        httpMethod: POST
        type: aws_proxy
      requestBody:
        content:
          application/json:
            schema:
              title: OTPRequest
              type: object
              description: Forma de contato onde a senha descartável, ou OTP (One-Time Password), será enviada.
              properties:
                email:
                  type: string
                  description: O endereço de e-mail do usuário.
                phoneNumber:
                  type: string
                  description: O número de telefone do usuário.
      responses:
        "200":
          description: Código enviado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  deviceId:
                    type: string
                    description: Identificador único gerado pelo Supertokens do dispositivo de onde o usuário está acessando.
                  flowType:
                    type: string
                    description: Tipo de auntenticação utilizada.
                  preAuthSessionId:
                    type: string
                    description: Identificador da sessão criada e gerenciada pelo Supertokens.
                  status:
                    type: string
                    description: Status de sucesso
      tags:
        - Sessions
    options:
      summary: Preflight
      description: Preflight request to enable CORS calls.
      security: []
      responses:
        "200":
          description: Default response for preflight
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode" : 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,fdi-version,rid,sec-ch-ua,sec-ch-ua-mobile,sec-ch-ua-platform,anti-csrf,supertokens-sdk-name,supertokens-sdk-version'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
            responseTemplates:
              application/json: "#set($context.responseOverride.header['Access-Control-Allow-Origin'] = $input.params().header.origin) {}"
```

**Comment by montedonioluiz** [comment]
So just as a feedback also @rishabhpoddar we basically had to manually implement a workaround with the CORS config; in the end we're basically implementing the response header `Access-Control-Allow-Origin: *` because both the OPTIONS calls and our services are retrieving the requests' `Origin` header and injecting it in the response `Access-Control-Allow-Origin` header.

I believe this would be a nice setup to have native in SuperTokens or in the Multi-tenancy feature you mentioned.

**Comment by rishabhpoddar** [comment]
I see. I'm not sure if setting the value to * will work though. Browsers will reject cookies in this setting. Am I misunderstanding what you are trying to do?

**Comment by montedonioluiz** [comment]
I'm not setting it to *; technically I'm setting it to the value of the request's Origin header. So if I make the request from www.supertokens-frontend.com, the value of the response header Access-Control-Allow-Origin will be www.supertokens-frontend.com. If I make the request from google.com, the response's header value will be google.com. We were able to dinamically create this as a mock response directly in the API Gateway definition (as shown in the last line of the yaml I previously sent here).

So the value of the header will never be `*`, however with this implementation we basically have the same effect; whoever accesses the endpoint will always have permission to do so, as the value of the header will always be the domain that makes the call.

**Comment by rishabhpoddar** [comment]
Ah I see. Makes sense.
