### ISSUE TITLE
Cookie expiry time issue

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#492]
The SDK makes the access token expiry time to 100 years from now, but when setting in chrome, chrome sets it to 1 year from now. Why is that? Also, if the access token's expiry time in the core is more than 1 year, what will happen to the cookie setting?

**Comment by porcellus** [comment]
Chrome (and Edge/chrome based browsers) limit cookie expiration to a bit over a year (see [here](https://developer.chrome.com/blog/cookie-max-age-expires/#:~:text=As%20of%20Chrome%20release%20M104,400%20days%20in%20the%20future.))
Firefox sets the cookie with the requested expiration time.

There is not much we can do about this - we can't opt out. 
This can only cause issues if the access token validity is set to over 400 days which is not advised anyway. In this case, the user is automatically logged out after 400 days and not use the refresh mechanism. We could limit the core setting to 400 days, but I'd rather just add a comment about this into the documentation of the config option.
