### ISSUE TITLE
Blank screen when loading user dashboard

### ISSUE THREAD

**Issue by korbinancell** [supertokens/supertokens-node#507]
https://discord.com/channels/603466164219281420/644849840475602944/1081356273544597534

When loading the user dashboard on localhost it looks like the script does not run and I end up with a blank screen with no failed network requests and no errors in the console.
I have supertokens set up in aws lambda as an auth service with my api on cloudflare workers as a reverse proxy for the service. The linked discord thread includes a har file of the requests.

Here is my backend config:
```js
{
    framework: "awsLambda",
    supertokens: {
      connectionURI: "***",
      apiKey: "***",
    },
    appInfo: {
      appName: "cay.com",
      apiDomain: "https://cay.com",
      websiteDomain: "https://cay.com",
      apiBasePath: "/auth",
      apiGatewayPath: "/prod",
    },
    recipeList: [
      Passwordless.init({
        flowType: "MAGIC_LINK",
        contactMethod: "EMAIL",
      }),
      Session.init(),
      Dashboard.init({
        apiKey: "***",
      }),
    ],
    isInServerlessEnv: true,
  }
```

and my FE config:
```js
{
  appInfo: {
    appName: "CAY",
    apiDomain: window.location.origin,
    apiBasePath: "/api/auth",
    websiteDomain: window.location.origin,
    websiteBasePath: "/auth",
  },
  recipeList: [
    Passwordless.init({
      contactMethod: "EMAIL",
    }),
    Session.init(),
  ],
}
```

**Comment by nkshah2** [comment]
The issue was related to the way requests were being proxied, there isnt a real fix that can be implemented here.

@korbinancell Ill close the issue for now, feel free to re-open if the issue persists
