### ISSUE TITLE
Error: SuperTokens core threw an error for a PUT request to path: '/recipe/user' with status code: 500 and message: Internal Error

### ISSUE THREAD

**Issue by sayhicoelho** [supertokens/supertokens-node#514]
I can't change the user's password using the ThirdPartyEmailPassword recipe.

I'm trying to run this piece of code taken from the docs:

![image](https://user-images.githubusercontent.com/8188365/225191581-c9c7fae2-7c06-48d5-8c06-d02565ae2bdf.png)

The response is:

![image](https://user-images.githubusercontent.com/8188365/225191854-78518b34-0fb5-44cb-8ba7-3f57f0a2fed4.png)

Frontend code:

![image](https://user-images.githubusercontent.com/8188365/225191991-ad74a3ff-8ba1-4963-83b6-4ef21e74c79b.png)

Backend code:

![image](https://user-images.githubusercontent.com/8188365/225192639-50172ded-6f86-432e-8a46-344909a0fdf8.png)

Docs:
https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/change-password#step-2-validate-and-update-the-users-password

**Comment by rishabhpoddar** [comment]
Hi. 
- What are the error logs on the core when you call this API?
- Did you manually delete entries in the emailpassword_users or the all_auth_users table?

**Comment by sayhicoelho** [comment]
@rishabhpoddar Hi. The only logs I have are the ones I uploaded in the issue. I don't know how to get logs you're requesting. Also, I haven't manually deleted any entries in the database.

**Comment by rishabhpoddar** [comment]
You can get the logs by seeing the docker logs output of the core process. If you are not using docker for the core, then you can find it in the logs folder in the installation directory.

Finally, if you are using our managed service, then you can [join our discord](https://supertokens.com/discord) and message me (my handle is rp) your email and i can have a look.

**Comment by rishabhpoddar** [comment]
We have identified the issue - we will release a new version of the core shortly.

**Comment by rishabhpoddar** [comment]
This has been fixed in core version >= 4.4.2

If you are using docker, then the docker tag is `4.4`, be sure to delete the older docker image and pull it again.

**Comment by sayhicoelho** [comment]
@rishabhpoddar I'm using the managed service. How can I use the updated version of supertokens-core? I tried to run the password change but got the same error.

**Comment by rishabhpoddar** [comment]
@sayhicoelho what's the email you used to sign up on supertokens.com? If you don't want to write it here, you can send me an email on rishabh@supertokens.com with your registered email ID.

**Comment by rishabhpoddar** [comment]
Should be working fine now @sayhicoelho - please try again.

**Comment by sayhicoelho** [comment]
Thanks @rishabhpoddar ! It worked, but the response is empty.

![image](https://user-images.githubusercontent.com/8188365/225961293-3665a7d5-1fef-4330-b1a2-5020022801c4.png)

The `else if (response.data.status === "OK")` is never reached.

![image](https://user-images.githubusercontent.com/8188365/225961370-4179ece5-14c9-41fc-acce-393fa302c18c.png)

**Comment by rishabhpoddar** [comment]
So the frontend should call your backend API to change the password. The backend API would then call the core. Therefore, the frontend should check for the response based on what your backend API sends. Based on the screenshot above, you do `res.end()` on the backend after succesful change in password, you do not send a JSON response - therefore the frontend won't get it.

About the password strength, that's a check that's done on the backend sdk level in the APIs that we expose via the middleware. So since you are making your own API here, you need to check the password strength yourself before calling the `updateEmailOrPassword` function
