### ISSUE TITLE
Unable to login to the User dashboard management (403)

### ISSUE THREAD

**Issue by Sohett** [supertokens/supertokens-node#525]
As per requested by support ([Discord](https://discord.com/channels/603466164219281420/644849840475602944/1088862082650341488)) I open an issue related to a bug I am facing while trying to login as an admin to the `User dashboard management`. I am using the Managed Service Core. 

Locally I can connect to the dashboard. Once hosted when I try to login on the dashboard, the request returns a `403` error. 

I am using the [serverless framework](https://www.serverless.com/) to deploy my NodeJs app on a lambda (hosted on AWS). 
I am using the  `"supertokens-node": "^13.1.5"` SDK on an `express` based app. 

![Screenshot_2023-03-24_at_17 16 52](https://user-images.githubusercontent.com/29751630/227719716-03ea090f-40f0-4ea6-b89e-ea37cf2c739b.png)

**Comment by rishabhpoddar** [comment]
The issue was that the `/prod` was being used as a way to scope the server and `apiGatewayPath: "/prod"` needed to be set on the backend's appInfo.
