### ISSUE TITLE
Password policy not enforced when changing password via `updateEmailOrPassword`

### ISSUE THREAD

**Issue by cyrilchapon** [supertokens/supertokens-node#549]
When signing up, a user is enforced to follow a password policy.
When changing his password through `updateEmailOrPassword`, this policy is not respected.

## Expected

```ts
updateEmailOrPassword({
  userId,
  password: "az"
})
```

to throw

## Actual

It "works", and defines the password to `az`

**Comment by rishabhpoddar** [comment]
This is an expected behaviour since it's a function that's called from your backend. The password policy is applied only to the API layer (which takes in user input).

This flexibility allows for developers to override the password policy in situations that they need to.

**Comment by cyrilchapon** [comment]
@rishabhpoddar 
> This is an expected behaviour

Frankly **this is not** for consumer (at least not in all cases). As a reminder, [Supertokens docs recommend this API usage](https://supertokens.com/docs/emailpassword/common-customizations/change-password) for a route called for signed in users from a frontend; even if it's not in the "API layer".

> This flexibility allows for developers to override the password policy in situations that they need to.

There is no flexibility at all, since developers cannot access the password policy; and are actually **forced** to override it.

This should be overrideable **IF** they need to.

----------

Simply, 

```ts
updateEmailOrPassword({
  userId,
  password: "az"
}, {
  applyPasswordPolicy: true
})
```


Nota bene : closing this is brutal...

**Comment by rishabhpoddar** [comment]
You are right. I think we can make it so that we add `applyPasswordPolicy` and by default it's `true` (so the password policy is applied), and if devs want to bypass it, they can make it false.

We will change the docs related to this in the meantime. Thanks for pointing this out (reopening this issue until it's solved)

**Comment by rishabhpoddar** [comment]
We have released new versions of the backend SDK which takes into account the password policy when the updateEmailOrPassword function is called:
- node sdk >= 14.0.0
- python SDK >= 0.13
- golang SDK >= 0.12
