### ISSUE TITLE
Unclear documentation about verify email sent momentum

### ISSUE THREAD

**Issue by cyrilchapon** [supertokens/supertokens-node#550]
I followed religiously the documentation about Email verification : https://supertokens.com/docs/emailpassword/common-customizations/email-verification/about

The thing is we're in a team and I'm only implementing the API.

I configured all the stuff, and gave it a shot by **signing up** a new user, naively thinking I would receive the email. I spent 2 hours digging, with debug mode all the way down, searching for Discord history, re-reading the doc...

...until I realized the `/auth/user/email/verify/token` will be called **by the frontend** and not automatically on signup... Or will it be ?

I'm still unsure as of now.

**Comment by rishabhpoddar** [comment]
You are right that the email verification API will be called by the frontend. We will make it more clear in our docs. Thanks

**Comment by jscyo** [comment]
Closing, since we have updated our docs to make this clear
