### ISSUE TITLE
Dashboard Login does not work when autofilling email/password

### ISSUE THREAD

**Issue by LukasKnuth** [supertokens/supertokens-node#555]
I have set up a dashboard user as per the CURL instruction. I then added it's username/password to 1Password to get auto filling.

When I then navigate to the login and auto-fill the username/password and click "Sign in", the email field shows "Email is invalid" and the password field shows "Password cannot be empty".

I suspect that this is due to auto-filling the values, because when I **type in** the exact same email/password or simply add and remove a space in both fields after the autofill does its thing, the Sign-In works as expected.

Let me know if more information is required, so that I can provide it.

**Comment by rishabhpoddar** [comment]
We have fixed the dashboard. To get the latest version, empty cache and hard reload
