### ISSUE TITLE
Edit USER METADATA in dashboard and delete all, "Looks like something went wrong!

### ISSUE THREAD

**Issue by araera111** [supertokens/supertokens-node#573]
If you update with {}, it will update normally with an empty.
It would be better to make it {} for all deletions as well, or to display a cautionary statement instead of completely failing with an error.

**Comment by nkshah2** [comment]
Hi @araera111 

Could you elaborate on the issue? What exactly did you try that resulted in an error?

**Comment by rishabhpoddar** [comment]
This has been fixed. Thanks.
