### ISSUE TITLE
Nested jwt present in newer access tokens preventing access

### ISSUE THREAD

**Issue by theholla** [supertokens/supertokens-node#601]
We're upgrading our NextJS / Hasura app to SuperTokens `5.0` and ran into an issue with existing sessions not refreshing.

Our hosted core SuperTokens instance was recently upgraded to `5.0` in our development environment. Users could log in as expected. But after deploying our backend changes, users reported a `Could not verify JWT: JWTExpired` error from Hasura on attempts to validate the token. We updated the backend SDK and client code as described in the [CHANGELOG](https://github.com/supertokens/supertokens-node/blob/master/CHANGELOG.md#1400---2023-05-04). 

Decoding either the `sAccessToken` or `st-access-token` cookie, they're both in the newer token format... but with an additional nested jwt field, like this:

```
{
  "sub": "1234",
  "exp": 1687462081,
  "iat": 1687458481,
  "sessionHandle": "a",
  "refreshTokenHash1": "b",
  "parentRefreshTokenHash1": "c",
  "antiCsrfToken": null,
  "https://hasura.io/jwt/claims": {...]
  },
  "jwt": "eyJra...", // unexpected
  "_jwtPName": "jwt"
}
```

The `exp` value on the issues token is not expired. But decoding the nested `jwt` value, that one is expired. Since there's a `jwt` field present on the response, the client code thinks it's the older issued access token and enters the `jwt !== undefined` block of the [seamless upgrade logic](https://github.com/supertokens/supertokens-node/blob/master/CHANGELOG.md#if-you-used-the-jwt-feature-of-the-session-recipe). It uses the expired token and we get that `JWTExpired` error from Hasura. 

Thank you!

Versions:
- `core`: currently at `5.0`
- `supertokens-node`: `^13.5.0` to `^14.1.1`
- `supertokens-web-js`: still on `^0.5.0`

**Comment by porcellus** [comment]
Hi, thanks for reporting this.
While we figure out a long-term solution (and/or an update to the recommended upgrade logic), a quick fix could be to check if you have the new version of the access token based on the `sub` prop instead of `jwt`:
```
let jwt = null;
const accessTokenPayload = await Session.getAccessTokenPayloadSecurely();
if (accessTokenPayload.sub !== undefined) {
    jwt = await Session.getAccessToken();
} else {
    // This branch is only required if there are valid access tokens created before the update
    // It can be removed after the validity period ends
    jwt = accessTokenPayload.jwt;
}
```

**Comment by theholla** [comment]
The recommended fix worked for us, thank you.
