### ISSUE TITLE
JWKs endpoint response expiration or validity period

### ISSUE THREAD

**Issue by theholla** [supertokens/supertokens-node#617]
Is it possible to know when exactly the JWKs will rotate for a given environment? For example by sending a `Cache-Control: max-age` header on the `/.well-known/jwks.json` response?

More on our use case:

We have a NextJS / Hasura / SuperTokens app deployed by Vercel. As outlined in the SuperTokens [NextJS Setup guide](https://supertokens.com/docs/thirdpartyemailpassword/nextjs/setting-up-backend), we overrode the auth endpoints with `no-cache, no-store, max-age=0, must-revalidate` headers to avoid Vercel's automatic caching.

A side effect of `max-age=0` on the JWKs auth endpoint was that Hasura started refreshing the JWKs [once per second](https://hasura.io/docs/latest/auth/authentication/jwt/#rotating-jwks). That ends up being really noisy and expensive. To fix this, we tried overriding the auth endpoints to cache just the JWKs endpoint response. That cut costs, but eventually we ran into a `JWSInvalidSignature` error from Hasura during the cache period during key rotation. Since Vercel was caching the response according to our headers, Hasura couldn't get the latest value.

If the `/.well-known/jwks.json` response could provide a `max-age` header, Hasura could refresh the JWK again after the time period specified in `max-age` has passed ([docs](https://hasura.io/docs/latest/auth/authentication/jwt/#jwk-procedure-while-running)).

Or, I'm curious if you know of another way we can reliably use dynamic signing keys with this tech stack. Thank you!

**Comment by rishabhpoddar** [comment]
Any updates on this @porcellus ?

**Comment by rishabhpoddar** [comment]
We have released a fix for this in node SDK version 15.1.0.
