### ISSUE TITLE
EmailPassword recipe: Email verification

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#62]
- This is related to https://github.com/supertokens/supertokens-core/issues/124
- The APIs exposed by this are [here](https://github.com/supertokens/supertokens-node/issues/62#issuecomment-751616106)
- The functions exposed are [here](https://github.com/supertokens/supertokens-node/issues/62#issuecomment-751616153).
- Config changes are [here](https://github.com/supertokens/supertokens-node/issues/62#issuecomment-752341799)

**Comment by rishabhpoddar** [comment]
# API exposed
TODO

**Comment by rishabhpoddar** [comment]
# Functions exposed
TODO

**Comment by NkxxkN** [comment]
We need to modify `SuperTokens.middleware` function to return an error when email is not verified.

**Comment by rishabhpoddar** [comment]
## Config changes
TODO

**Comment by rishabhpoddar** [comment]
@NkxxkN , in the config, should we have a post email verification success callback? So that user's can send a welcome email etc.. when the email is verified?

**Comment by NkxxkN** [comment]
We have a `handleSuccess` callback already implemented in the front end after email was successfully verified. Let's say this is enough and if they want to send an email on successful email verification the starting point should be the front end.

**Comment by rishabhpoddar** [comment]
- It feels a bit odd that a function like sending a welcome email after email verification is initiated from a frontend callback
- In the optional method, we may not have that callback? In that case, it may break the flow
- Having a backend callback will make it consistent with the sign up feature -> we have a callback on the backend and frontend for that too.

**Comment by bhumilsarvaiya** [comment]
#### Supertokens API endpoint used to send email verification link
**API Endpoint**: `/0/st/auth/email/verify`
**Method**: `POST`
**Success Response**: `{}`
**Success Response Code**: `200`
**Possible Response Codes**: `200, 400, 408, 500`
**Required in Request**:
- headers:
    - api-version: 0
- request-body:
   ```
   {
       email: string,
       appName: string,
       emailVerifyURL: string
   }
   ```

**Comment by rishabhpoddar** [comment]
Looks good. I assume that this is almost identical to the password reset email API?

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar yes, it is identical to that one

**Comment by NkxxkN** [comment]
> In the optional method, we may not have that callback? In that case, it may break the flow

We will have it.

We can also have something in the backend if we do already for sign in sign up then. That makes sense
