### ISSUE TITLE
Dashboard doesn't display "Is Email Verified" correctly.

### ISSUE THREAD

**Issue by jzhao321** [supertokens/supertokens-node#661]
![image](https://github.com/supertokens/supertokens-node/assets/43896564/e53e1ab7-b203-4ee8-867e-5039e571e2ba)
![image](https://github.com/supertokens/supertokens-node/assets/43896564/b025e47d-d63a-4d83-977c-db96e5a4268d)

Even though the Email is verified when inspecting the database, the front end dashboard shows "Is Email Verified" as no.

supertokens-node@15.0.0
supertokens-web-js@0.7.1
next@13.4.12
express@4.18.2
react@18.2.0
typescript@5.1.6

**Comment by nkshah2** [comment]
Hey @jzhao321 

This is fixed in supertokens-node 15.0.2, closing this issue for now but feel free to reopen if the issue persists
