### ISSUE TITLE
Issue with delete user in Dashboard

### ISSUE THREAD

**Issue by matindexifi** [supertokens/supertokens-node#663]
Getting the error below when deleting a user in the dashboard 

**Dashboard page**
```
Looks like something went wrong!
Please refresh the page to try again or contact us if the error persists.
```

**Front end response**
```
{
    "statusCode": 400,
    "code": "FST_ERR_CTP_EMPTY_JSON_BODY",
    "error": "Bad Request",
    "message": "Body cannot be empty when content-type is set to 'application/json'"
}
```
**Backend console**
`api | 17:52:25 🌲 Body cannot be empty when content-type is set to 'application/json'`

Using 
- supertokens-node 15.0
- 6.0 supertokens managed instance
- redwood 6.0.2

**Comment by nkshah2** [comment]
Hi @matindexifi 

We have released a fix in the dashboard UI repository for this. To verify please clear cache and reload the dashboard. Closing this but feel free to re-open if the issue persists
