### ISSUE TITLE
Send verification email if email verification mode is "REQUIRED" on signup

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-node#67]
On signup, when email verification is "REQUIRED", you get redirected to 

![image](https://user-images.githubusercontent.com/5072452/103995710-20f97e80-5199-11eb-9a03-34dedb09b94f.png)

But no email was sent. You need to click on "Resend Email" to receive it.

We should send the email on signup. The problem is that we don't know in the backend if email verification is turned on.

Two options:
 - Add to backend init.
 - Send as a param with the signup request

**Comment by rishabhpoddar** [comment]
I prefer if the frontend calls the API to send the email when this screen shows up - as if the user clicked on the resen button automatically. I prefer this because if we have to send the email on our own via the backend, we will need to know the email verification mode on the backend too - so the user will have to add that on frontend and backend, which is more annoying.

**Comment by NkxxkN** [comment]
Sounds good. Closing

**Comment by wlucjan** [comment]
@rishabhpoddar I was wondering - if only FE knows about email verification being enabled, doesn't it open a scenario, when someone manipulating JS and removing the requirement on FE could create user account with unverified email? am I missing anything?

**Comment by rishabhpoddar** [comment]
@wlucjan you are right. It does. We are working on a fix for this where we embed info about email verification in the session and check for it via the access token on each API call that assumes email verification to be done.

In the meantime, you can add that in the access token payload yourself on session creation and then:
- update the payload info post email verification (via API overrides)
- check in each of your API if the access token payload indicates if the email is verified or not.

The above in conjunction with what we have already would work well from a security point of view.
