### ISSUE TITLE
Not able to work with multiple frontends with different domains with the same Supertokens instance

### ISSUE THREAD

**Issue by chadybadour** [supertokens/supertokens-node#676]
i using a self hosted supertokens instance, it was connected to a single frontend react app.
Now i added another frontend app with different domain and i want to connect it to the same supertokens instance ?

Is it possible to do it ?

**Comment by rishabhpoddar** [comment]
Hey. This is possible. But this type of question is more appropriate for support on [our discord](https://supertokens.com/discord). So im closing the issue here.
