### ISSUE TITLE
next/with-emailpassword example doesn't work

### ISSUE THREAD

**Issue by exKAZUu** [supertokens/supertokens-node#699]
Reproduction steps
1. `git clone https://github.com/supertokens/supertokens-node.git`
2. `cd supertokens-node`
3. `npm i`
4. `cd examples/next/with-emailpassword`
5. `npm i`
6. `npm run dev`
7. Open http://localhost:3000/
8. The following error is shown:

```
Unhandled Runtime Error
NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
```

<img width="889" alt="image" src="https://github.com/supertokens/supertokens-node/assets/436237/d389f263-f9fc-46d9-bc17-78c62c747399">

**Comment by rtpa25** [comment]
npm currently does not support local packages satisfactorily. I recommend authors to use yarn instead when using file based refs inside example directory.

**Comment by rishabhpoddar** [comment]
Hey! Whilst we fix this, in the mean time, try out our CLI instead - `npx create-supertokens-app@latest`.

**Comment by nkshah2** [comment]
Hi @exKAZUu The example app in supertokens-node isnt recommended to be used directly anymore (its mainly present for internal testing). You can use the command @rishabhpoddar posted to set up an app. Closing this issue because theres no action needed here

**Comment by exKAZUu** [comment]
I see. Thank you for the explanation :bow:

**Comment by exKAZUu** [comment]
@rishabhpoddar @nkshah2 How can I create an example based on `next/with-emailpassword` in this repository?

If I select `Next.js` and `Email Password`, an example based on https://github.com/supertokens/next.js/tree/canary/examples/with-supertokens seems to be generated.

```
create-supertokens-app (v0.0.38) lets you quickly get started with using SuperTokens!
Choose your tech stack and the authentication method, we will create a working project that uses SuperTokens for you.
? What is your app called? my-app
? Choose a frontend framework (Visit our documentation for integration with other frameworks): Next.js
? What type of authentication do you want to use? Email Password
```

The example uses only the pages router, but, I need the example using the app router like https://github.com/supertokens/supertokens-node/tree/master/examples/next/with-emailpassword

**Comment by nkshah2** [comment]
@exKAZUu 

The frontend SDK does not fully support the new app directory yet

**Comment by exKAZUu** [comment]
I understand. Thanks!
