### ISSUE TITLE
fastify compatibility

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-node#727]
We need to verify/fix our compatibility with the latest (4.X) fastify versions. The lib depends on types from an outdated (prev major version) fastify.

**Comment by woss** [comment]
hi, yeah. this should be quite high on the list.

**Comment by rishabhpoddar** [comment]
This is already fixed for now i think. So closing it

**Comment by woss** [comment]
@rishabhpoddar  https://github.com/supertokens/supertokens-node/blob/master/package.json#L155 it seems it's not. 

the pacakge.json still references the v3

**Comment by rishabhpoddar** [comment]
Thats just for tests, it doesn't actually affect the compatibility with later versions of fastify.
