### ISSUE TITLE
Hello, I wanted to create a custom login to paypal

### ISSUE THREAD

**Issue by marcin86mak** [supertokens/supertokens-node#734]
The problem is logging client_id and client_secret in PayPal. This process is done by Heders
curl -v -X POST "https://api-m.sandbox.paypal.com/v1/oauth2/token"
  -u "CLIENT_ID:CLIENT_SECRET"

Note: Encode CLIENT_ID:CLIENT_SECRET in Base64 before sending it in the API call.

What is needed is access to the Request Headers:
tokenEndpointBodyParams => OK
tokenEndpointHeaders -> None, please add it, it will solve the problem it describes.

Thank you in advance.
And I'm looking forward to seeing this fix implemented as soon as possible.
Best regards, Marcin....

**Comment by marcin86mak** [comment]
You can also create the entire configuration for PayPal

{
                            // return (bool) $this->isSandbox ? 'https://www.sandbox.paypal.com' : 'https://www.paypal.com';
                            // return (bool) $this->isSandbox ? 'https://api-m.sandbox.paypal.com' : 'https://api-m.paypal.com';
                            config: {
                                thirdPartyId: "paypal",
                                clients: [
                                    {
                                        clientType: "web-and-android",
                                        clientId: "xxxx", 
                                        clientSecret: "xxxx",
                                    },
                                ],
                                authorizationEndpoint: "https://www.sandbox.paypal.com/signin/authorize",
                                authorizationEndpointQueryParams: {},
                                tokenEndpoint: "https://api-m.sandbox.paypal.com/v1/oauth2/token",
                                tokenEndpointBodyParams:{},
                                userInfoEndpoint: "https://api-m.sandbox.paypal.com/v1/identity/openidconnect/userinfo?schema=openid",
                                userInfoMap: {
                                    fromUserInfoAPI: {
                                        userId: "user_id",
                                        email: "email",
                                        emailVerified: "email_verified",
                                    }
                                }
                            },
                        },

**Comment by sattvikc** [comment]
Please try the following snippet for login with paypay:

```ts
{
    config: {
        thirdPartyId: "paypal",
        name: "Paypal",
        clients: [
            {
                clientId: "AcUPr89LCOzyhuJ4q-pNyMFhnDRsEAx779yLLKF0ZNvqjFHqCjUVYPqbgyttT2IP-UcI5tQY5z0W5p9l",
                clientSecret: "EIiU-1BYeLYIVTbstqSmPh4rumgFiADEoOvcHgHLAlqvBCtxLHf6_XkcbuMiL7jeB-a_B17OEau19ipJ",
                scope: ["openid", "email"]
            },
        ],
        authorizationEndpoint: "https://www.sandbox.paypal.com/signin/authorize",
        tokenEndpoint: "https://api-m.sandbox.paypal.com/v1/oauth2/token",
        userInfoEndpoint: "https://api.sandbox.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1",
        userInfoMap: {
            fromUserInfoAPI: {
                userId: "user_id"
            }
        }
    },
    override: (oI) => {
        oI.exchangeAuthCodeForOAuthTokens = async (input) => {
            const clientId = oI.config.clientId;
            const clientSecret = oI.config.clientSecret;
            const basicAuthToken = Buffer.from(
                `${clientId}:${clientSecret}`,
                "utf8"
            ).toString("base64");
            const paypalOauthParams = {
                grant_type: "authorization_code",
                code: input.redirectURIInfo.redirectURIQueryParams.code,
            };
            const querystring = require('querystring');
            const formData = querystring.stringify(paypalOauthParams);
            const headers = {
                'Authorization': `Basic ${basicAuthToken}`,
                'Content-Type': 'application/x-www-form-urlencoded'
            };

            const resp = await axios.post(oI.config.tokenEndpoint!, formData, { headers });
            console.log(resp);
            return resp.data;
        }
        
        return oI;
    }
}
```
