### ISSUE TITLE
Build error in next.js when using `runtime = 'edge'`

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-node#745]
This causes an error: `Module not found: Can't resolve 'zlib'` (same for querystring and crypto) during building and running in dev mode.

Reproduction:
Using our nextjs example, add
```
export const runtime = 'edge';
```
to the user route https://github.com/supertokens/next.js/blob/canary/examples/with-supertokens/app/api/user/route.ts reproduces the issue.

Reported in: https://discordapp.com/channels/603466164219281420/1173443361550643250

**Comment by rishabhpoddar** [comment]
This issue has been solved in node sdk >= 20
