### ISSUE TITLE
Bugs in built in provider ( LinkedIn ): LinkedIn removed api "/v2/me", "/emailAddress" and changed their oauth scopes in their latest api 

### ISSUE THREAD

**Issue by Sotatek-MinhPham2** [supertokens/supertokens-node#751]
Bugs in built in provider ( LinkedIn ): LinkedIn removed api "https://api.linkedin.com/v2/me",  "https://api.linkedin.com/v2/emailAddress" and changed their oauth scopes again
![Screenshot from 2023-12-05 01-01-28](https://github.com/supertokens/supertokens-node/assets/103913422/a5ceefcf-76dd-48a9-8c2f-6544edf85fe2)

**Comment by rishabhpoddar** [comment]
Thanks for pointing this out. We have fixed this for our node and python SDKs. Keeping this issue open until we also fix it for golang.

**Comment by rishabhpoddar** [comment]
This issue has been fixed for all of our backend SDKs.
