### ISSUE TITLE
Handle null values in jwtPayload and sessionData more gracefully

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#77]
Allow the user to give `null` in `createNewSession` and other functions that update session payloads. We can handle this by checking for null and setting it to `undefined` instead.

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar should it be `undefined` or `{}` (which is also the default value if user has not passed any value)?

**Comment by rishabhpoddar** [comment]
{} should be fine.
