### ISSUE TITLE
Allow the user to change jwtPayload and sessionData in sign up or sign in API

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#78]

**Comment by bhumilsarvaiya** [comment]
We can do this by allowing user to pass additional parameters during `signup` and `signin` APIs (for **EmailPassword** Recipe) and during `signinup` API (for **ThirdParty** Recipe). New CDI version will be created. The changes will be backward compatible with the existing supported CDI version.

**Comment by rishabhpoddar** [comment]
No. We need to provide a user a callback in the nodeSDK which they can override to provide session data / jwt payload that the API can use when creating a new session. This callback will take the userId (or user object) as the input.

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar okay got it. So in the configs for sign-in/up, we allow user to pass a function that will return jwtPayload and sessionData. This function will be given user object. Should we also give the request object to this callback function? Sometimes the information that needs to be stored in the jwtPayload/sessionData also depends on the data passed from frontend to backend in either request body or request param.

**Comment by rishabhpoddar** [comment]
For emailpassword, we won't pass the req object. We will pass the formField input. For thirdparty, we will pass the user and the authorisationcode API response.
