### ISSUE TITLE
Use of Supertokens Dashboard in offline environments

### ISSUE THREAD

**Issue by djuelg** [supertokens/supertokens-node#818]
Hi, I am currently working on implementing a user management solution with Supertokens. I have planned to run the solution in an environment without internet access.  

However, if I see it correctly, it is not possible to use the dashboard without internet as it is loaded via the getDashboardBundleLocation method from the hardcoded address cdn.jsdelivr.net. Are there any plans to mitigate this problem in the future or to offer configuration options?

Kind regards, Dominik

**Comment by rishabhpoddar** [comment]
You can always override that api in dashboard.init on the backend to return a bundle from somewhere else that you like. I think that can work.

**Comment by djuelg** [comment]
Thanks, that helped! The solution looks something like this:

```js
Dashboard.init({
            override: {
                functions: (originalImplementation) => {
                    return {
                        ...originalImplementation,
                        getDashboardBundleLocation: async function () {
                            return `https://MY-LOCAL-CDN/dashboard@0.11.1/build/`;
                        }
                    }
                }
            }
        })
```

**Comment by rishabhpoddar** [comment]
Hopefully they fix it soon!
