### ISSUE TITLE
Using .local TLD for apiDomian or websiteDomain leads to parsing error

### ISSUE THREAD

**Issue by tobiasbeck** [supertokens/supertokens-node#823]
Parsing .local tlds leads to a `Please make sure that the apiDomain and websiteDomain have correct values` error.

The reason for this is that `psl`, which is used under the hood to validate the url is not parsing .local tld's ([see here](https://github.com/lupomontero/psl/blob/a789d0381c886da02eb8594da0761860657c08ba/index.js#L180)) which leads to a the mentioned error.

**Comment by rishabhpoddar** [comment]
Whats the use case of using `.local` tlds? If it's not there in that list, it's not an actual TLD right? Maybe I am missing something here.

**Comment by tobiasbeck** [comment]
In my case I'm using Orbstack as my container runtime during development.
Orbstack automatically generates domains ([documentation](https://docs.orbstack.dev/docker/domains#compose-projects)) for the development containers following the schema `<container-name>.orb.local`, which are only accessible locally since .local only routes in the local network it would make sense in my eyes to not validate it, just like its already done with localhost domains.

**Comment by rishabhpoddar** [comment]
Fair enough. Thanks for the info. We will work on fixing this.

**Comment by rishabhpoddar** [comment]
This has been fixed in node sdk version >= 17.0.5
