### ISSUE TITLE
Advanced configuration of FaunaDB Client

### ISSUE THREAD

**Issue by heracek** [supertokens/supertokens-node#83]
## Problem

- I run FaunaDB in Docker for local development (https://hub.docker.com/r/fauna/faunadb)
- to make it work work I have to setup `faunadb.Client({ ... })` with `domain` and `port` configuration
  - with `supertokens-node` I can only pass `secret` [see here](https://github.com/supertokens/supertokens-node/blob/48be5eaf7e2eea0cb77b205843b57d7f37aeeb5b/lib/ts/recipe/session/faunadb/sessionRecipe.ts#L80-L82)
- I'd like to be able to provide [all possible configuration](https://github.com/fauna/faunadb-js/blob/master/src/types/Client.d.ts#L9-L20) to `faunadb.Client({ ... })`

## Possible solution:

I see two possible solutions:
1. add `{ faunaClientConfig?: faunadb.ClientConfig }` to session config for advance setup
2. add `{ faunaClient?: faunadb.Client }` to session config so I can configure the fauna any way I like from outside and pass the instance to SuperTokens
    - this solution could improve testability of your code too 😉 

If you wold be interested I could prepare some PR for this.

**Comment by rishabhpoddar** [comment]
Thanks @heracek! We would love a PR for this if you can. Otherwise, we will get it working ASAP regardless :)

**Comment by rishabhpoddar** [comment]
@heracek have fixed this issue. It's in branch `3.4` of the node repo. Will ping back here once the SDK has been released.

Please refer to the [updated docs](https://supertokens.io/docs/emailpassword/common-customizations/sessions/using-with-faunadb#3-add-faunadb-options-to-the-sessioninit-function). If this still shows the older `faunadbSecret`, then you may need to hard reload, or view this page on our [test site instead](https://test.supertokens.io/docs/emailpassword/common-customizations/sessions/using-with-faunadb#3-add-faunadb-options-to-the-sessioninit-function).

**Comment by heracek** [comment]
Thanks @rishabhpoddar,
you were fast with the PR, seems to be exactly what I wanted. I'll test it in my setup.

I've created at least PR for improvements of types around faunadb session management: #84

**Comment by rishabhpoddar** [comment]
@heracek I have released the new version `v.3.4.1`.
