### ISSUE TITLE
SuperTokens SMTP Delivery - Nodemailer

### ISSUE THREAD

**Issue by DarkNeedle** [supertokens/supertokens-node#848]
Appears SuperTokens depends on Nodemailer for SMTP delivery (standard SMTP server)? Defining SMTP server info using the passwordless example results in:

Error: The edge runtime does not support Node.js 'stream' module. (This appears to be from Nodemailer as it does not support Edge runtimes).

**Comment by rishabhpoddar** [comment]
Hey. We are aware of this issue. To et around this, you can define your own custom sendEmail function (https://supertokens.com/docs/passwordless/email-delivery/custom-method) in which you can use any library you like to send emails.

**Comment by rishabhpoddar** [comment]
It works for non edge cases. I agree that the issue has been open since one year, however, since there is a rather straightforward workaround, it's very low in our list of priorities.

**Comment by rishabhpoddar** [comment]
So there does not seem to be library that supports edge runtime, so instead, you should use an email sending service like AWS SES, mailchimp, sendgrid or resend. To use these, you can override the sendEmail function in the backend config and call the APIs for these services: https://supertokens.com/docs/passwordless/email-delivery/custom-method
