### ISSUE TITLE
Static provider list behaviour for non-public tenants

### ISSUE THREAD

**Issue by sattvikc** [supertokens/supertokens-node#891]
Statically initilised provider list shows up on all tenants by default, which doesn't seem right. Especially when using SAML.

By default, the static init providers should only show up for public tenant. If users want to make them also show up for non public tenants, they can add a boolean to them like addToNonPublicTenantsByDefault: true:
- If providers from core is [] and we are public tenants, then we merge with static config (current behaviour)
- If providers from core is != [] and we are public tenant, we use providers from core (current behaviour)
- If providers from core is [] and we are NON public tenants, then we merge with static config, only those providers that have addToNonPublicTenantsByDefault: true (new behaviour)
- If providers from core is != [] and we are NON public tenant, we use providers from core (current behaviour)

**Comment by rishabhpoddar** [comment]
This has been released in node sdk version >= 20.0.0
