### ISSUE TITLE
Upgrade to Fastify v5

### ISSUE THREAD

**Issue by victormamede** [supertokens/supertokens-node#945]
Hi, supertokens' fastify integration is still using fastify 4, the latest version is 5. Besides some typescript errors i didn't notice any breaking changes, perhaps we could fix that and upgrade to version 5?

**Comment by rishabhpoddar** [comment]
Hi. The dependency we have in our node sdk is only for testing purposes. Otherwise integration with fastify v5 sohuld work fine. Are you seeing any errors with the latest node sdk we have?

**Comment by victormamede** [comment]
As far as I tested it is working fine, the only thing is that I have to put this ugly `any` or some @ts-ignore rule on this line
```typescript
app.setErrorHandler(errorHandler() as any);
```
I'm reading the code to see if there's any breaking change that we need to keep in mind but so far it looks ok, I could try and fix these type issues and open a PR

**Comment by rishabhpoddar** [comment]
We will be releasing a fix for this in our next major release (v21.0) sometime this or next week

**Comment by victormamede** [comment]
Thank you!
