### ISSUE TITLE
Possibility of header stripping might ruin how rId based routing works

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#99]
To fix this, we should completely eliminate header based routing and perhaps switch to path based routing. Something like `/{apiBasePath}/{rId}/<api path>`

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar What about passing `rId` passed as a query parameter?

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya doing that for POST requests is a little weird, isn't it?

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar Maybe it's weird. We can also send `rId` in POST body but instead of complicating stuff like that, we can go with the your suggest of passing `rId` in path

**Comment by rishabhpoddar** [comment]
Coding due to inactivity. Also this custom header is needed to prevent CSRF attacks.
